/**
 * Top-level generator for form validators.
 *
 * For every endpoint whose request body is a Triad schema (typically a
 * model), we emit:
 *
 *   - A typed `validateXxx(input)` function that returns
 *     `{ ok: true, value } | { ok: false, errors }`.
 *   - Optional wrapper(s) for popular form libraries when requested:
 *     - `react-hook-form` via `xxxResolver()`
 *     - `@tanstack/form` via `xxxValidator`
 *
 * Output layout:
 *
 * ```
 * client/forms/
 *   runtime.ts          — minimal evaluator (~140 lines)
 *   types.ts            — every named interface used by validators
 *   <context>.ts        — one file per bounded context with validators
 *   react-hook-form.ts  — (optional) resolver wrappers
 *   tanstack-form.ts    — (optional) validator wrappers
 *   index.ts            — barrel
 * ```
 */

import type { Endpoint, Router, SchemaNode } from '@triadjs/core';
import { TypeEmitter, toPascal } from '@triadjs/tanstack-query';
import type { GenerateOptions, GeneratedFile } from './types.js';
import { describeSchema, type FormFieldDesc } from './descriptor.js';
import { RUNTIME_SOURCE } from './runtime.js';

const HEADER = `// Generated by @triadjs/forms — do not edit.
// Regenerate with: triad frontend generate --target forms\n`;

interface ValidatorMeta {
  /** Generated function name, e.g. `validateCreateBook`. */
  fnName: string;
  /** TypeScript type the validator produces, e.g. `CreateBook`. */
  tsType: string;
  /** PascalCase label used in wrapper emitters, e.g. `CreateBook`. */
  label: string;
  /** File slug where the validator lives (e.g. `library`). */
  slug: string;
}

export function generate(router: Router, options: GenerateOptions): GeneratedFile[] {
  const emitter = new TypeEmitter();
  const contextFiles = new Map<
    string,
    { slug: string; items: Array<{ endpoint: Endpoint; desc: FormFieldDesc; meta: ValidatorMeta }> }
  >();
  const allMeta: ValidatorMeta[] = [];

  const addToContext = (ctxName: string, ep: Endpoint): void => {
    if (ep.request.body === undefined) return;
    const body = ep.request.body as SchemaNode;
    const desc = describeSchema(body);
    if (desc.kind !== 'object') {
      // Non-object bodies (e.g. raw string) aren't form-shaped.
      return;
    }
    const tsType = emitter.emitType(body);
    const label = toPascal(ep.name);
    const slug = slugify(ctxName);
    const meta: ValidatorMeta = {
      fnName: `validate${label}`,
      tsType,
      label,
      slug,
    };
    const bucket = contextFiles.get(slug);
    if (bucket === undefined) {
      contextFiles.set(slug, { slug, items: [{ endpoint: ep, desc, meta }] });
    } else {
      bucket.items.push({ endpoint: ep, desc, meta });
    }
    allMeta.push(meta);
  };

  for (const ep of router.rootEndpoints) addToContext('root', ep);
  for (const ctx of router.contexts) {
    for (const ep of ctx.endpoints) addToContext(ctx.name, ep);
  }

  const hookFiles: GeneratedFile[] = [];
  for (const [slug, bucket] of contextFiles) {
    const typeRefs = new Set<string>();
    const fnBlocks: string[] = [];
    for (const item of bucket.items) {
      typeRefs.add(item.meta.tsType);
      fnBlocks.push(renderValidator(item.meta, item.desc));
    }
    const imports: string[] = [];
    imports.push(`import { validateWith, type ValidationResult } from './runtime.js';`);
    const typeImports = Array.from(typeRefs)
      .filter((ref) => emitter.has(ref))
      .sort();
    if (typeImports.length > 0) {
      imports.push(`import type { ${typeImports.join(', ')} } from './types.js';`);
    }
    const contents = `${HEADER}\n${imports.join('\n')}\n\n${fnBlocks.join('\n\n')}\n`;
    hookFiles.push({ path: `${slug}.ts`, contents });
  }

  // types.ts
  const typeLines: string[] = [HEADER];
  for (const nt of emitter.namedTypes()) {
    typeLines.push(nt.source);
    typeLines.push('');
  }
  if (emitter.namedTypes().length === 0) {
    typeLines.push('export {};');
  }

  // index.ts barrel
  const indexLines: string[] = [
    HEADER,
    `export * from './runtime.js';`,
    `export * from './types.js';`,
  ];
  for (const f of hookFiles) {
    const base = f.path.replace(/\.ts$/, '');
    indexLines.push(`export * from './${base}.js';`);
  }
  if (options.reactHookForm === true) {
    indexLines.push(`export * from './react-hook-form.js';`);
  }
  if (options.tanstackForm === true) {
    indexLines.push(`export * from './tanstack-form.js';`);
  }

  const files: GeneratedFile[] = [
    { path: 'runtime.ts', contents: RUNTIME_SOURCE },
    { path: 'types.ts', contents: `${typeLines.join('\n')}\n` },
    ...hookFiles,
    { path: 'index.ts', contents: `${indexLines.join('\n')}\n` },
  ];

  if (options.reactHookForm === true) {
    files.push({
      path: 'react-hook-form.ts',
      contents: renderReactHookFormWrappers(allMeta),
    });
  }
  if (options.tanstackForm === true) {
    files.push({
      path: 'tanstack-form.ts',
      contents: renderTanstackFormWrappers(allMeta),
    });
  }

  return files;
}

function renderValidator(meta: ValidatorMeta, desc: FormFieldDesc): string {
  const descJson = JSON.stringify(desc, null, 2);
  const lines: string[] = [];
  lines.push(`const ${meta.fnName}Descriptor = ${descJson} as const;`);
  lines.push(`export function ${meta.fnName}(input: unknown): ValidationResult<${meta.tsType}> {`);
  lines.push(`  return validateWith<${meta.tsType}>(${meta.fnName}Descriptor, input);`);
  lines.push(`}`);
  return lines.join('\n');
}

function renderReactHookFormWrappers(metas: readonly ValidatorMeta[]): string {
  // Emit a tiny wrapper per validator that adapts our ValidationResult
  // to the react-hook-form Resolver shape. We intentionally type the
  // resolver signature loosely (as `unknown`) so the generated file
  // compiles without pulling `react-hook-form` types.
  const lines: string[] = [HEADER];
  lines.push(
    `import type { ValidationResult, ValidationError } from './runtime.js';`,
  );
  // Dedupe import lines per slug: group validators by slug.
  const bySlug = groupBySlug(metas);
  for (const [slug, group] of bySlug) {
    const names = group.map((m) => m.fnName).sort();
    lines.push(`import { ${names.join(', ')} } from './${slug}.js';`);
  }
  lines.push('');
  for (const meta of metas) {
    lines.push(renderRhfResolver(meta));
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}

function renderRhfResolver(meta: ValidatorMeta): string {
  return (
    `export function ${lowerFirst(meta.label)}Resolver() {\n` +
    `  return async (values: unknown): Promise<{ values: unknown; errors: Record<string, { type: string; message: string }> }> => {\n` +
    `    const result: ValidationResult<unknown> = ${meta.fnName}(values);\n` +
    `    if (result.ok) return { values: result.value, errors: {} };\n` +
    `    const errors: Record<string, { type: string; message: string }> = {};\n` +
    `    for (const err of result.errors as readonly ValidationError[]) {\n` +
    `      errors[err.path] = { type: err.code, message: err.message };\n` +
    `    }\n` +
    `    return { values: {}, errors };\n` +
    `  };\n` +
    `}`
  );
}

function renderTanstackFormWrappers(metas: readonly ValidatorMeta[]): string {
  const lines: string[] = [HEADER];
  lines.push(`import type { ValidationResult } from './runtime.js';`);
  const bySlug = groupBySlug(metas);
  for (const [slug, group] of bySlug) {
    const names = group.map((m) => m.fnName).sort();
    lines.push(`import { ${names.join(', ')} } from './${slug}.js';`);
  }
  lines.push('');
  for (const meta of metas) {
    lines.push(
      `export const ${lowerFirst(meta.label)}Validator = {\n` +
        `  onChange: (input: unknown): string | undefined => {\n` +
        `    const result: ValidationResult<unknown> = ${meta.fnName}(input);\n` +
        `    if (result.ok) return undefined;\n` +
        `    return result.errors.map((e) => \`\${e.path}: \${e.message}\`).join('; ');\n` +
        `  },\n` +
        `};`,
    );
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}

function groupBySlug(
  metas: readonly ValidatorMeta[],
): Map<string, ValidatorMeta[]> {
  const out = new Map<string, ValidatorMeta[]>();
  for (const m of metas) {
    const bucket = out.get(m.slug);
    if (bucket === undefined) out.set(m.slug, [m]);
    else bucket.push(m);
  }
  return out;
}

function slugify(name: string): string {
  return (
    name
      .replace(/[^A-Za-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .toLowerCase() || 'root'
  );
}

function lowerFirst(input: string): string {
  if (input.length === 0) return input;
  return input.charAt(0).toLowerCase() + input.slice(1);
}
