/**
 * Source for the runtime validator template that lives alongside the
 * generated validators. Kept as a string so the generator has no
 * runtime import cycle back into `@triad/core`.
 */

export const RUNTIME_SOURCE = `// Generated by @triad/forms. Safe to edit or replace.
// Minimal schema evaluator that mirrors the subset of Triad's schema
// kinds needed for form validation (required/optional, primitive
// types, enums, literals, arrays, nested objects).

export type FormFieldKind =
  | 'string'
  | 'number'
  | 'boolean'
  | 'datetime'
  | 'enum'
  | 'literal'
  | 'array'
  | 'object'
  | 'unknown';

export interface FormFieldDesc {
  kind: FormFieldKind;
  optional: boolean;
  nullable: boolean;
  values?: readonly (string | number)[];
  literal?: string | number | boolean;
  item?: FormFieldDesc;
  fields?: Record<string, FormFieldDesc>;
}

export interface ValidationError {
  path: string;
  message: string;
  code: string;
}

export type ValidationResult<T> =
  | { ok: true; value: T }
  | { ok: false; errors: ValidationError[] };

export function validateWith<T>(
  desc: FormFieldDesc,
  input: unknown,
): ValidationResult<T> {
  const errors: ValidationError[] = [];
  const value = validateNode(desc, input, '', errors);
  if (errors.length > 0) {
    return { ok: false, errors };
  }
  return { ok: true, value: value as T };
}

function validateNode(
  desc: FormFieldDesc,
  input: unknown,
  path: string,
  errors: ValidationError[],
): unknown {
  if (input === undefined || input === '') {
    if (desc.optional) return undefined;
    errors.push({ path, code: 'required', message: 'Field is required' });
    return undefined;
  }
  if (input === null) {
    if (desc.nullable) return null;
    errors.push({ path, code: 'null_not_allowed', message: 'Field may not be null' });
    return null;
  }
  switch (desc.kind) {
    case 'string':
    case 'datetime':
      if (typeof input !== 'string') {
        errors.push({ path, code: 'invalid_type', message: 'Expected string' });
      }
      return input;
    case 'number': {
      const num = typeof input === 'string' ? Number(input) : input;
      if (typeof num !== 'number' || Number.isNaN(num)) {
        errors.push({ path, code: 'invalid_type', message: 'Expected number' });
        return input;
      }
      return num;
    }
    case 'boolean':
      if (typeof input !== 'boolean') {
        errors.push({ path, code: 'invalid_type', message: 'Expected boolean' });
      }
      return input;
    case 'enum': {
      const vs = desc.values ?? [];
      if (!vs.includes(input as string | number)) {
        errors.push({
          path,
          code: 'not_in_enum',
          message: \`Expected one of: \${vs.join(', ')}\`,
        });
      }
      return input;
    }
    case 'literal': {
      if (input !== desc.literal) {
        errors.push({
          path,
          code: 'literal_mismatch',
          message: \`Expected \${JSON.stringify(desc.literal)}\`,
        });
      }
      return input;
    }
    case 'array': {
      if (!Array.isArray(input)) {
        errors.push({ path, code: 'invalid_type', message: 'Expected array' });
        return input;
      }
      if (desc.item === undefined) return input;
      return input.map((v: unknown, i: number) =>
        validateNode(desc.item as FormFieldDesc, v, \`\${path}[\${i}]\`, errors),
      );
    }
    case 'object': {
      if (typeof input !== 'object' || input === null || Array.isArray(input)) {
        errors.push({ path, code: 'invalid_type', message: 'Expected object' });
        return input;
      }
      const out: Record<string, unknown> = {};
      const record = input as Record<string, unknown>;
      const fields = desc.fields ?? {};
      for (const [fieldName, fieldDesc] of Object.entries(fields)) {
        const childPath = path === '' ? fieldName : \`\${path}.\${fieldName}\`;
        const child = validateNode(fieldDesc, record[fieldName], childPath, errors);
        if (child !== undefined || fieldName in record) {
          out[fieldName] = child;
        }
      }
      return out;
    }
    default:
      return input;
  }
}
`;
