/**
 * Top-level generator for Solid Query hooks.
 *
 * Output layout mirrors `@triad/tanstack-query`:
 *
 * ```
 * client/
 *   index.ts       — barrel re-exporting everything
 *   types.ts       — named interfaces
 *   query-keys.ts  — per-resource key factories
 *   client.ts      — runtime fetch client (reused verbatim)
 *   <context>.ts   — one file per bounded context with its hooks
 * ```
 */

import type { Endpoint, Router } from '@triad/core';
import {
  TypeEmitter,
  emitKeyFactory,
  extractResource,
  flatKeyFor,
  renderClient,
  toPascal,
  type ResourceInfo,
} from '@triad/tanstack-query';
import type { GenerateOptions, GeneratedFile } from './types.js';
import { renderSolidHook, type HookRenderContext } from './hook-generator.js';

const HEADER = `// Generated by @triad/solid-query — do not edit.
// Regenerate with: triad frontend generate --target solid-query\n`;

export function generate(router: Router, options: GenerateOptions): GeneratedFile[] {
  const baseUrl = options.baseUrl ?? '/api';
  const emitRuntime = options.emitRuntime ?? true;
  const emitter = new TypeEmitter();

  const contextFiles = new Map<string, { slug: string; endpoints: Endpoint[] }>();
  const addToContext = (ctxName: string, ep: Endpoint): void => {
    const slug = slugify(ctxName);
    const bucket = contextFiles.get(slug);
    if (bucket !== undefined) {
      bucket.endpoints.push(ep);
      return;
    }
    contextFiles.set(slug, { slug, endpoints: [ep] });
  };
  for (const ep of router.rootEndpoints) addToContext('root', ep);
  for (const ctx of router.contexts) {
    for (const ep of ctx.endpoints) addToContext(ctx.name, ep);
  }

  const resourcesByName = new Map<string, ResourceInfo>();
  const flatKeys: { name: string; value: string }[] = [];
  const allEndpoints = router.allEndpoints();
  for (const endpoint of allEndpoints) {
    const info = extractResource(endpoint.path);
    if (info !== undefined) {
      const existing = resourcesByName.get(info.resource);
      if (existing === undefined) {
        resourcesByName.set(info.resource, info);
      } else if (existing.idParam === undefined && info.idParam !== undefined) {
        resourcesByName.set(info.resource, { ...existing, idParam: info.idParam });
      }
    } else {
      flatKeys.push(flatKeyFor(endpoint));
    }
  }

  // Render each bounded-context file.
  const hookFiles: GeneratedFile[] = [];
  for (const [slug, bucket] of contextFiles) {
    const renderCtx: HookRenderContext = { availableResources: resourcesByName };
    const hookSources: string[] = [];
    const typeRefs = new Set<string>();
    const resourceRefs = new Set<string>();
    let usesFlatKey = false;
    let usesQuery = false;
    let usesMutation = false;

    for (const endpoint of bucket.endpoints) {
      const info = extractResource(endpoint.path);
      const ctxForEndpoint: HookRenderContext =
        info !== undefined
          ? { ...renderCtx, resource: resourcesByName.get(info.resource) }
          : renderCtx;
      const hook = renderSolidHook(endpoint, emitter, ctxForEndpoint);
      for (const ref of hook.typeRefs) typeRefs.add(ref);
      if (info !== undefined) {
        resourceRefs.add(resourcesByName.get(info.resource)!.factoryName);
      } else {
        usesFlatKey = true;
      }
      if (endpoint.method === 'GET') usesQuery = true;
      else usesMutation = true;
      hookSources.push(hook.source);
    }

    const imports: string[] = [];
    const sqImports: string[] = [];
    if (usesQuery) {
      sqImports.push('createQuery', 'type SolidQueryOptions');
    }
    if (usesMutation) {
      sqImports.push(
        'createMutation',
        'useQueryClient',
        'type SolidMutationOptions',
      );
    }
    if (sqImports.length > 0) {
      imports.push(`import { ${sqImports.join(', ')} } from '@tanstack/solid-query';`);
    }
    imports.push(`import { client, type HttpError } from './client.js';`);
    const typeImports = Array.from(typeRefs)
      .filter((ref) => emitter.has(ref) || isEndpointShapeType(ref))
      .sort();
    if (typeImports.length > 0) {
      imports.push(`import type { ${typeImports.join(', ')} } from './types.js';`);
    }
    const keyImports: string[] = [];
    for (const r of resourceRefs) keyImports.push(r);
    if (usesFlatKey) {
      for (const endpoint of bucket.endpoints) {
        if (extractResource(endpoint.path) === undefined) {
          keyImports.push(flatKeyFor(endpoint).name);
        }
      }
    }
    if (keyImports.length > 0) {
      const unique = Array.from(new Set(keyImports)).sort();
      imports.push(`import { ${unique.join(', ')} } from './query-keys.js';`);
    }

    const contents = `${HEADER}\n${imports.join('\n')}\n\n${hookSources.join('\n\n')}\n`;
    hookFiles.push({ path: `${slug}.ts`, contents });
  }

  // query-keys.ts
  const keyLines: string[] = [HEADER];
  for (const info of resourcesByName.values()) {
    const listEndpoint = allEndpoints.find((e) => {
      if (e.method !== 'GET') return false;
      const r = extractResource(e.path);
      return r !== undefined && r.resource === info.resource && r.idParam === undefined;
    });
    const listParamsType =
      listEndpoint !== undefined && listEndpoint.request.query !== undefined
        ? `${toPascal(listEndpoint.name)}Query`
        : undefined;
    keyLines.push(emitKeyFactory(info, listParamsType));
    keyLines.push('');
  }
  for (const flat of flatKeys) {
    keyLines.push(`export const ${flat.name} = ${flat.value};`);
  }
  if (resourcesByName.size > 0 || flatKeys.length > 0) {
    const imports: string[] = [];
    for (const info of resourcesByName.values()) {
      const listEndpoint = allEndpoints.find((e) => {
        if (e.method !== 'GET') return false;
        const r = extractResource(e.path);
        return r !== undefined && r.resource === info.resource && r.idParam === undefined;
      });
      if (listEndpoint !== undefined && listEndpoint.request.query !== undefined) {
        imports.push(`${toPascal(listEndpoint.name)}Query`);
      }
    }
    if (imports.length > 0) {
      keyLines.splice(1, 0, `import type { ${imports.join(', ')} } from './types.js';`, '');
    }
  }

  // types.ts
  const typeLines: string[] = [HEADER];
  for (const nt of emitter.namedTypes()) {
    typeLines.push(nt.source);
    typeLines.push('');
  }
  if (emitter.namedTypes().length === 0) {
    typeLines.push('export {};');
  }

  // index.ts barrel
  const indexLines: string[] = [
    HEADER,
    `export * from './types.js';`,
    `export * from './query-keys.js';`,
    `export * from './client.js';`,
  ];
  for (const f of hookFiles) {
    const base = f.path.replace(/\.ts$/, '');
    indexLines.push(`export * from './${base}.js';`);
  }

  const files: GeneratedFile[] = [
    { path: 'types.ts', contents: `${typeLines.join('\n')}\n` },
    { path: 'query-keys.ts', contents: `${keyLines.join('\n')}\n` },
    ...hookFiles,
    { path: 'index.ts', contents: `${indexLines.join('\n')}\n` },
  ];

  if (emitRuntime) {
    files.push({ path: 'client.ts', contents: renderClient({ baseUrl }) });
  }

  return files;
}

function slugify(name: string): string {
  return (
    name
      .replace(/[^A-Za-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .toLowerCase() || 'root'
  );
}

const ENDPOINT_SHAPE_SUFFIXES = /(Params|Query|Headers)$/;
function isEndpointShapeType(name: string): boolean {
  return ENDPOINT_SHAPE_SUFFIXES.test(name);
}

