/**
 * Unit tests for the schema-to-fake-data walker used by `triad mock`.
 *
 * Every fake value generated by `fakeFromSchema` MUST pass through the
 * schema's own `parse()` so the mock server never serves data the
 * schema would reject.
 */

import { describe, expect, it } from 'vitest';
import { t } from '@triad/core';
import { fakeFromSchema } from '../src/schema-fake.js';

describe('fakeFromSchema', () => {
  it('fakes a plain string that parses', () => {
    const s = t.string();
    const v = fakeFromSchema<string>(s);
    expect(typeof v).toBe('string');
    expect(s.parse(v)).toBe(v);
  });

  it('respects string min/max length', () => {
    const s = t.string().minLength(5).maxLength(10);
    const v = fakeFromSchema<string>(s);
    expect(v.length).toBeGreaterThanOrEqual(5);
    expect(v.length).toBeLessThanOrEqual(10);
    expect(s.parse(v)).toBe(v);
  });

  it('fakes uuid format with a valid uuid', () => {
    const s = t.string().format('uuid');
    const v = fakeFromSchema<string>(s);
    expect(v).toMatch(/^[0-9a-f-]{36}$/i);
    expect(s.parse(v)).toBe(v);
  });

  it('fakes email format', () => {
    const s = t.string().format('email');
    const v = fakeFromSchema<string>(s);
    expect(v).toContain('@');
    expect(s.parse(v)).toBe(v);
  });

  it('fakes int32 within bounds', () => {
    const s = t.int32().min(10).max(20);
    const v = fakeFromSchema<number>(s);
    expect(Number.isInteger(v)).toBe(true);
    expect(v).toBeGreaterThanOrEqual(10);
    expect(v).toBeLessThanOrEqual(20);
  });

  it('fakes a float', () => {
    const s = t.float64();
    const v = fakeFromSchema<number>(s);
    expect(typeof v).toBe('number');
    s.parse(v);
  });

  it('fakes a boolean', () => {
    const s = t.boolean();
    const v = fakeFromSchema<boolean>(s);
    expect(typeof v).toBe('boolean');
  });

  it('fakes a datetime as an ISO string', () => {
    const s = t.datetime();
    const v = fakeFromSchema<string>(s);
    expect(() => new Date(v).toISOString()).not.toThrow();
    s.parse(v);
  });

  it('fakes an enum with the first variant', () => {
    const s = t.enum('a', 'b', 'c');
    const v = fakeFromSchema<string>(s);
    expect(v).toBe('a');
    s.parse(v);
  });

  it('fakes a literal with its value', () => {
    const s = t.literal('hello');
    const v = fakeFromSchema<string>(s);
    expect(v).toBe('hello');
  });

  it('fakes an array of three elements', () => {
    const s = t.array(t.int32());
    const v = fakeFromSchema<number[]>(s);
    expect(Array.isArray(v)).toBe(true);
    expect(v.length).toBe(3);
    s.parse(v);
  });

  it('fakes a model with every field', () => {
    const Pet = t.model('Pet', {
      id: t.string().format('uuid'),
      name: t.string().minLength(1),
      age: t.int32().min(0).max(30),
    });
    const v = fakeFromSchema<{ id: string; name: string; age: number }>(Pet);
    expect(typeof v.id).toBe('string');
    expect(typeof v.name).toBe('string');
    expect(typeof v.age).toBe('number');
    Pet.parse(v);
  });

  it('fakes a union with the first variant', () => {
    const s = t.union(t.literal('on'), t.literal('off'));
    const v = fakeFromSchema<string>(s);
    expect(v).toBe('on');
  });

  it('fakes a tuple element by element', () => {
    const s = t.tuple(t.string(), t.int32());
    const v = fakeFromSchema<[string, number]>(s);
    expect(Array.isArray(v)).toBe(true);
    expect(v.length).toBe(2);
    expect(typeof v[0]).toBe('string');
    expect(Number.isInteger(v[1])).toBe(true);
  });

  it('fakes an optional field as undefined or a valid value', () => {
    const Model = t.model('M', {
      maybe: t.string().optional(),
      required: t.string(),
    });
    const v = fakeFromSchema<{ maybe?: string; required: string }>(Model);
    Model.parse(v);
  });

  it('produces identical output for the same seed', () => {
    const Pet = t.model('Pet', {
      id: t.string().format('uuid'),
      name: t.string(),
      age: t.int32(),
    });
    const a = fakeFromSchema(Pet, { seed: 42 });
    const b = fakeFromSchema(Pet, { seed: 42 });
    expect(a).toEqual(b);
  });

  it('fakes an unknown schema as null', () => {
    const s = t.unknown();
    const v = fakeFromSchema(s);
    expect(v).toBeNull();
  });
});
