/**
 * Source of the runtime fetch client that is emitted alongside the
 * generated hooks. Kept as a plain string template so the generator
 * has no runtime dependency on `fetch`/DOM types itself.
 */

export interface ClientTemplateOptions {
  baseUrl: string;
}

export function renderClient(options: ClientTemplateOptions): string {
  const baseUrl = JSON.stringify(options.baseUrl);
  return `// Generated by @triadjs/tanstack-query. Safe to edit or replace.
// This is the runtime fetch client the hooks depend on. Swap it for
// your own implementation (e.g. to add auth headers or interceptors)
// as long as you preserve the method signatures.

export interface RequestOptions {
  query?: Readonly<Record<string, unknown>> | object;
  headers?: Record<string, string>;
  body?: unknown;
  signal?: AbortSignal;
}

export class HttpError extends Error {
  constructor(
    public readonly code: string,
    message: string,
    public readonly status: number,
    public readonly details?: unknown,
  ) {
    super(message);
    this.name = 'HttpError';
  }
}

export class TriadClient {
  constructor(private readonly baseUrl: string = ${baseUrl}) {}

  async get<T>(path: string, opts: RequestOptions = {}): Promise<T> {
    return this.request<T>('GET', path, opts);
  }
  async post<T>(path: string, opts: RequestOptions = {}): Promise<T> {
    return this.request<T>('POST', path, opts);
  }
  async put<T>(path: string, opts: RequestOptions = {}): Promise<T> {
    return this.request<T>('PUT', path, opts);
  }
  async patch<T>(path: string, opts: RequestOptions = {}): Promise<T> {
    return this.request<T>('PATCH', path, opts);
  }
  async delete<T>(path: string, opts: RequestOptions = {}): Promise<T> {
    return this.request<T>('DELETE', path, opts);
  }

  private async request<T>(method: string, path: string, opts: RequestOptions): Promise<T> {
    const url = new URL(this.baseUrl + path, typeof window !== 'undefined' ? window.location.origin : 'http://localhost');
    if (opts.query) {
      for (const [k, v] of Object.entries(opts.query as Record<string, unknown>)) {
        if (v === undefined || v === null) continue;
        url.searchParams.set(k, String(v));
      }
    }
    const init: RequestInit = {
      method,
      headers: {
        ...(opts.body !== undefined ? { 'Content-Type': 'application/json' } : {}),
        ...(opts.headers ?? {}),
      },
    };
    if (opts.body !== undefined) {
      init.body = JSON.stringify(opts.body);
    }
    if (opts.signal !== undefined) {
      init.signal = opts.signal;
    }
    const res = await fetch(url.toString(), init);
    if (!res.ok) {
      let payload: { code?: string; message?: string; details?: unknown } = {};
      try {
        payload = await res.json();
      } catch {
        // non-JSON error body — fall through with defaults
      }
      throw new HttpError(
        payload.code ?? 'UNKNOWN',
        payload.message ?? res.statusText,
        res.status,
        payload.details,
      );
    }
    if (res.status === 204 || res.status === 205 || res.status === 304) {
      return undefined as T;
    }
    return (await res.json()) as T;
  }
}

export const client = new TriadClient();
`;
}
