/**
 * Top-level generator: given a Triad router, produce the list of files
 * to write into the user's frontend output directory.
 *
 * Output layout:
 *
 * ```
 * client/
 *   index.ts         — barrel re-exporting everything
 *   types.ts         — every named interface used by any hook
 *   query-keys.ts    — per-resource key factories
 *   client.ts        — runtime fetch client + HttpError
 *   <context>.ts     — one file per bounded context with its hooks
 * ```
 *
 * Root-level endpoints (no bounded context) are emitted into `root.ts`.
 */

import type { Endpoint, Router, BoundedContext } from '@triadjs/core';
import type { GenerateOptions, GeneratedFile } from './types.js';
import { TypeEmitter } from './schema-to-ts.js';
import {
  extractResource,
  emitKeyFactory,
  flatKeyFor,
  groupByResource,
  lowerFirst,
  toPascal,
  type ResourceInfo,
} from './query-keys.js';
import {
  collectEndpointShape,
  renderHook,
  type HookRenderContext,
} from './hook-generator.js';
import { renderClient } from './client.js';

const HEADER = `// Generated by @triadjs/tanstack-query — do not edit.
// Regenerate with: triad frontend generate --target tanstack-query\n`;

export function generate(router: Router, options: GenerateOptions): GeneratedFile[] {
  const baseUrl = options.baseUrl ?? '/api';
  const emitRuntime = options.emitRuntime ?? true;
  const emitter = new TypeEmitter();

  // Gather context groupings.
  const contextFiles: Map<string, { endpoints: Endpoint[]; slug: string }> = new Map();
  const fileFor = (contextName: string, endpoint: Endpoint): void => {
    const slug = slugify(contextName);
    const existing = contextFiles.get(slug);
    if (existing) {
      existing.endpoints.push(endpoint);
      return;
    }
    contextFiles.set(slug, { slug, endpoints: [endpoint] });
  };

  for (const endpoint of router.rootEndpoints) {
    fileFor('root', endpoint);
  }
  for (const context of router.contexts) {
    for (const endpoint of context.endpoints) {
      fileFor(context.name, endpoint);
    }
  }

  // Collect resource infos across every endpoint so query-keys.ts
  // emits one factory per resource even if the same resource is
  // used across multiple contexts.
  const resourcesByName = new Map<string, ResourceInfo>();
  const flatKeys: { name: string; value: string }[] = [];
  const allEndpoints = router.allEndpoints();
  for (const endpoint of allEndpoints) {
    const info = extractResource(endpoint.path);
    if (info !== undefined) {
      if (!resourcesByName.has(info.resource)) {
        resourcesByName.set(info.resource, info);
      } else {
        // Merge id param if any endpoint introduces a detail route.
        const existing = resourcesByName.get(info.resource)!;
        if (existing.idParam === undefined && info.idParam !== undefined) {
          resourcesByName.set(info.resource, { ...existing, idParam: info.idParam });
        }
      }
    } else {
      flatKeys.push(flatKeyFor(endpoint));
    }
  }

  // Walk endpoints once to build shapes (and therefore register types).
  const endpointShapes = new Map<string, ReturnType<typeof collectEndpointShape>>();
  for (const endpoint of allEndpoints) {
    const shape = collectEndpointShape(endpoint, emitter);
    endpointShapes.set(endpoint.name, shape);
  }

  // Now render hook files. Hooks reference types by name but imports
  // are collected at the file level.
  const hookFiles: GeneratedFile[] = [];
  for (const [slug, bucket] of contextFiles) {
    const renderCtx: HookRenderContext = {
      availableResources: resourcesByName,
    };
    const hookSources: string[] = [];
    const typeRefs = new Set<string>();
    const resourceRefs = new Set<string>();
    let usesFlatKey = false;
    let usesMutation = false;
    let usesQuery = false;

    for (const endpoint of bucket.endpoints) {
      const shape = endpointShapes.get(endpoint.name)!;
      const info = extractResource(endpoint.path);
      const ctxForEndpoint: HookRenderContext = info !== undefined
        ? { ...renderCtx, resource: resourcesByName.get(info.resource) }
        : renderCtx;
      const hook = renderHook(endpoint, shape, ctxForEndpoint);
      for (const ref of hook.typeRefs) typeRefs.add(ref);
      if (info !== undefined) {
        resourceRefs.add(resourcesByName.get(info.resource)!.factoryName);
      } else {
        usesFlatKey = true;
      }
      if (endpoint.method === 'GET') {
        usesQuery = true;
      } else {
        usesMutation = true;
      }
      hookSources.push(hook.source);
    }

    const imports: string[] = [];
    const rqImports: string[] = [];
    if (usesQuery) {
      rqImports.push('useQuery', 'type UseQueryOptions', 'type UseQueryResult');
    }
    if (usesMutation) {
      rqImports.push(
        'useMutation',
        'useQueryClient',
        'type UseMutationOptions',
        'type UseMutationResult',
      );
    }
    if (rqImports.length > 0) {
      imports.push(`import { ${rqImports.join(', ')} } from '@tanstack/react-query';`);
    }
    imports.push(`import { client, HttpError } from './client.js';`);
    const typeImports = Array.from(typeRefs)
      .filter((ref) => emitter.has(ref) || isEndpointShapeType(ref))
      .sort();
    if (typeImports.length > 0) {
      imports.push(`import type { ${typeImports.join(', ')} } from './types.js';`);
    }
    const keyImports: string[] = [];
    for (const r of resourceRefs) keyImports.push(r);
    if (usesFlatKey) {
      for (const endpoint of bucket.endpoints) {
        if (extractResource(endpoint.path) === undefined) {
          keyImports.push(flatKeyFor(endpoint).name);
        }
      }
    }
    if (keyImports.length > 0) {
      const unique = Array.from(new Set(keyImports)).sort();
      imports.push(`import { ${unique.join(', ')} } from './query-keys.js';`);
    }

    const contents = `${HEADER}\n${imports.join('\n')}\n\n${hookSources.join('\n\n')}\n`;
    hookFiles.push({ path: `${slug}.ts`, contents });
  }

  // query-keys.ts
  const keyLines: string[] = [HEADER];
  for (const info of resourcesByName.values()) {
    const listEndpoint = allEndpoints.find((e) => {
      if (e.method !== 'GET') return false;
      const r = extractResource(e.path);
      return r !== undefined && r.resource === info.resource && r.idParam === undefined;
    });
    const listParamsType =
      listEndpoint !== undefined && listEndpoint.request.query !== undefined
        ? `${toPascal(listEndpoint.name)}Query`
        : undefined;
    keyLines.push(emitKeyFactory(info, listParamsType));
    keyLines.push('');
  }
  for (const flat of flatKeys) {
    keyLines.push(`export const ${flat.name} = ${flat.value};`);
  }
  if (resourcesByName.size > 0 || flatKeys.length > 0) {
    // Figure out which list-params types need importing
    const imports: string[] = [];
    for (const info of resourcesByName.values()) {
      const listEndpoint = allEndpoints.find((e) => {
        if (e.method !== 'GET') return false;
        const r = extractResource(e.path);
        return r !== undefined && r.resource === info.resource && r.idParam === undefined;
      });
      if (listEndpoint !== undefined && listEndpoint.request.query !== undefined) {
        imports.push(`${toPascal(listEndpoint.name)}Query`);
      }
    }
    if (imports.length > 0) {
      keyLines.splice(1, 0, `import type { ${imports.join(', ')} } from './types.js';`, '');
    }
  }

  // types.ts
  const typeLines: string[] = [HEADER];
  for (const nt of emitter.namedTypes()) {
    typeLines.push(nt.source);
    typeLines.push('');
  }
  if (emitter.namedTypes().length === 0) {
    typeLines.push('export {};');
  }

  // index.ts barrel
  const indexLines: string[] = [HEADER, `export * from './types.js';`, `export * from './query-keys.js';`, `export * from './client.js';`];
  for (const f of hookFiles) {
    const base = f.path.replace(/\.ts$/, '');
    indexLines.push(`export * from './${base}.js';`);
  }

  const files: GeneratedFile[] = [
    { path: 'types.ts', contents: `${typeLines.join('\n')}\n` },
    { path: 'query-keys.ts', contents: `${keyLines.join('\n')}\n` },
    ...hookFiles,
    { path: 'index.ts', contents: `${indexLines.join('\n')}\n` },
  ];

  if (emitRuntime) {
    files.push({ path: 'client.ts', contents: renderClient({ baseUrl }) });
  }

  return files;
}

function slugify(name: string): string {
  return name
    .replace(/[^A-Za-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase() || 'root';
}

const ENDPOINT_SHAPE_SUFFIXES = /(Params|Query|Headers)$/;
function isEndpointShapeType(name: string): boolean {
  return ENDPOINT_SHAPE_SUFFIXES.test(name);
}

// Unused but kept to document intent; lowerFirst is used elsewhere.
void lowerFirst;
void slugify;
