import { describe, expect, it } from 'vitest';
import { createRouter, endpoint, scenario, t } from '@triad/core';
import type { ServiceContainer } from '@triad/core';
import { auto } from '../../core/src/scenario-auto.js';
import { runBehaviors } from '../src/runner.js';

// ---------------------------------------------------------------------------
// Schemas & endpoints with auto scenarios
// ---------------------------------------------------------------------------

const Pet = t.model('Pet', {
  id: t.string().format('uuid'),
  name: t.string().minLength(1).maxLength(50),
  species: t.enum('dog', 'cat', 'bird'),
  age: t.int32().min(0).max(30),
});
const CreatePet = Pet.pick('name', 'species', 'age').named('CreatePet');
const ApiError = t.model('ApiError', {
  code: t.string(),
  message: t.string(),
});

let petIdCounter = 0;

const createPet = endpoint({
  name: 'createPet',
  method: 'POST',
  path: '/pets',
  summary: 'Create a pet',
  request: { body: CreatePet },
  responses: {
    201: { schema: Pet, description: 'Created' },
    400: { schema: ApiError, description: 'Validation error' },
  },
  handler: async (ctx) => {
    const id = (++petIdCounter).toString().padStart(12, '0');
    return ctx.respond[201]({
      id: `00000000-0000-4000-8000-${id}`,
      name: ctx.body.name,
      species: ctx.body.species,
      age: ctx.body.age,
    });
  },
  behaviors: [
    scenario('creates a pet with valid data')
      .given('valid pet data')
      .body({ name: 'Buddy', species: 'dog', age: 5 })
      .when('I create a pet')
      .then('response status is 201'),
    ...auto(),
  ],
});

const listPets = endpoint({
  name: 'listPets',
  method: 'GET',
  path: '/pets',
  summary: 'List pets',
  responses: {
    200: {
      schema: t.model('PetList', { items: t.array(Pet) }),
      description: 'OK',
    },
  },
  handler: async (ctx) => ctx.respond[200]({ items: [] }),
  behaviors: [
    scenario('lists pets').given('no pets').when('I list pets').then('response status is 200'),
  ],
});

function buildRouter() {
  petIdCounter = 0;
  const router = createRouter({ title: 'TestAPI', version: '1.0.0' });
  router.add(createPet, listPets);
  return router;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('runner auto-scenario integration', () => {
  it('endpoint with auto() produces expanded scenarios in run', async () => {
    const router = buildRouter();
    const summary = await runBehaviors(router);
    // The hand-written scenario + auto-generated ones
    expect(summary.total).toBeGreaterThan(2);
  });

  it('auto scenarios appear with [auto:] prefix in scenario name', async () => {
    const router = buildRouter();
    const summary = await runBehaviors(router);
    const autoResults = summary.results.filter((r) => r.scenario.startsWith('[auto:'));
    expect(autoResults.length).toBeGreaterThan(0);
  });

  it('rejected outcome auto scenarios assert 400 for invalid input', async () => {
    const router = buildRouter();
    const summary = await runBehaviors(router);
    const missingResults = summary.results.filter((r) =>
      r.scenario.startsWith('[auto:missing]'),
    );
    // All missing-field scenarios should pass (the handler validates and returns 400)
    for (const result of missingResults) {
      expect(result.status).toBe('passed');
    }
  });

  it('accepted outcome auto scenarios verify non-500 response', async () => {
    const router = buildRouter();
    const summary = await runBehaviors(router);
    const validResults = summary.results.filter((r) =>
      r.scenario.startsWith('[auto:valid]'),
    );
    for (const result of validResults) {
      expect(result.status).toBe('passed');
    }
  });

  it('hand-written and auto scenarios run together', async () => {
    const router = buildRouter();
    const summary = await runBehaviors(router);
    const handWritten = summary.results.filter((r) => !r.scenario.startsWith('[auto:'));
    const autoGenerated = summary.results.filter((r) => r.scenario.startsWith('[auto:'));
    expect(handWritten.length).toBeGreaterThan(0);
    expect(autoGenerated.length).toBeGreaterThan(0);
  });

  it('auto scenarios only appear for endpoints that declared them', async () => {
    const router = buildRouter();
    const summary = await runBehaviors(router);
    const listAutoResults = summary.results.filter(
      (r) => r.endpointName === 'listPets' && r.scenario.startsWith('[auto:'),
    );
    // listPets does NOT have auto(), so no auto scenarios
    expect(listAutoResults).toHaveLength(0);
  });

  it('no auto scenarios when auto({ missingFields: false, boundaries: false, invalidEnums: false, typeConfusion: false, randomValid: 0 })', async () => {
    const minimalEp = endpoint({
      name: 'minimal',
      method: 'POST',
      path: '/minimal',
      summary: 'Minimal',
      request: { body: CreatePet },
      responses: {
        201: { schema: Pet, description: 'Created' },
        400: { schema: ApiError, description: 'Bad' },
      },
      handler: async (ctx) =>
        ctx.respond[201]({
          id: '00000000-0000-4000-8000-000000000001',
          name: ctx.body.name,
          species: ctx.body.species,
          age: ctx.body.age,
        }),
      behaviors: [
        ...auto({
          missingFields: false,
          boundaries: false,
          invalidEnums: false,
          typeConfusion: false,
          randomValid: 0,
        }),
      ],
    });
    const router = createRouter({ title: 'MinAPI', version: '1.0.0' });
    router.add(minimalEp);
    const summary = await runBehaviors(router);
    expect(summary.total).toBe(0);
  });
});
