/**
 * Dialect emitters. Turn `TableDescriptor[]` into TypeScript source for
 * either SQLite (`drizzle-orm/sqlite-core`) or Postgres
 * (`drizzle-orm/pg-core`).
 *
 * Both emitters share everything except the column-helper mapping:
 *
 *   - header text
 *   - table wrapper (`sqliteTable` vs `pgTable`)
 *   - column call chain (references → notNull → primaryKey → unique → default)
 *   - default expression emission
 *   - JS literal quoting
 *
 * Per-dialect work is localized to a `DialectProfile`:
 *
 *   - `columnHelper(column)` — which Drizzle column helper to use
 *   - `columnOptions(column)` — extra args passed to the helper
 *   - the import module and table helper name
 *
 * The output is deterministic (stable ordering, stable whitespace) so
 * generated files diff cleanly and snapshot tests stay stable.
 */

import type {
  ColumnDescriptor,
  Dialect,
  GenerateOptions,
  TableDescriptor,
} from './types.js';

export interface EmitOptions extends GenerateOptions {
  /**
   * Relative path (from the output file) shown in the header comment.
   * Purely informational.
   */
  sourceDescription?: string;
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

const HEADER_TEMPLATE = `/**
 * Generated by \`triad db generate\`.
 * Do not edit by hand — changes will be overwritten on the next run.
 *
 * Source: Triad router at {SOURCE}
 * Dialect: {DIALECT}
 */
`;

function buildHeader(dialect: Dialect, options: EmitOptions): string {
  return HEADER_TEMPLATE.replace(
    '{SOURCE}',
    options.sourceDescription ?? 'the configured router',
  ).replace('{DIALECT}', dialect);
}

// ---------------------------------------------------------------------------
// Dialect profiles
// ---------------------------------------------------------------------------

interface DialectProfile {
  dialect: Dialect;
  importModule: string;
  tableHelper: string; //  'sqliteTable' | 'pgTable'
  /** Map a column descriptor to the Drizzle column helper function name. */
  columnHelper: (column: ColumnDescriptor) => string;
  /**
   * Return the JS options object literal (e.g. `"{ mode: 'boolean' }"`)
   * for a column, or `undefined` if no options are needed.
   */
  columnOptions: (column: ColumnDescriptor) => string | undefined;
}

const SQLITE: DialectProfile = {
  dialect: 'sqlite',
  importModule: 'drizzle-orm/sqlite-core',
  tableHelper: 'sqliteTable',
  columnHelper: (column) => {
    switch (column.logicalType) {
      case 'string':
      case 'uuid':
      case 'datetime':
      case 'enum':
      case 'json':
        return 'text';
      case 'integer':
      case 'bigint':
      case 'boolean':
        return 'integer';
      case 'float':
      case 'double':
        return 'real';
    }
  },
  columnOptions: (column) => {
    const parts: string[] = [];
    if (column.logicalType === 'boolean') {
      parts.push("mode: 'boolean'");
    }
    if (column.logicalType === 'enum' && column.enumValues) {
      parts.push(
        `enum: [${column.enumValues.map((v) => `'${v}'`).join(', ')}]`,
      );
    }
    return parts.length > 0 ? `{ ${parts.join(', ')} }` : undefined;
  },
};

const POSTGRES: DialectProfile = {
  dialect: 'postgres',
  importModule: 'drizzle-orm/pg-core',
  tableHelper: 'pgTable',
  columnHelper: (column) => {
    switch (column.logicalType) {
      case 'string':
      case 'enum':
        return 'text';
      case 'uuid':
        return 'uuid';
      case 'datetime':
        return 'timestamp';
      case 'integer':
        return 'integer';
      case 'bigint':
        return 'bigint';
      case 'float':
        return 'real';
      case 'double':
        return 'doublePrecision';
      case 'boolean':
        return 'boolean';
      case 'json':
        return 'jsonb';
    }
  },
  columnOptions: (column) => {
    const parts: string[] = [];
    if (column.logicalType === 'datetime') {
      // `mode: 'string'` returns ISO strings from Postgres, matching
      // Triad's `t.datetime()` output type (string, not Date).
      parts.push("mode: 'string'");
    }
    if (column.logicalType === 'bigint') {
      // Return JS numbers rather than BigInts — matches Triad's int64,
      // whose TypeScript output type is `number`.
      parts.push("mode: 'number'");
    }
    if (column.logicalType === 'enum' && column.enumValues) {
      parts.push(
        `enum: [${column.enumValues.map((v) => `'${v}'`).join(', ')}]`,
      );
    }
    return parts.length > 0 ? `{ ${parts.join(', ')} }` : undefined;
  },
};

/**
 * MySQL mapping decisions (documented here for future maintainers):
 *
 *   - `string` → `varchar`. MySQL has no unbounded string type that's
 *     indexable with default settings, and `text` can't be part of a
 *     primary key without a prefix length. `varchar` with an explicit
 *     length is the safe default. When the author specified
 *     `.maxLength(n)` we honour it; otherwise we use 255, a common
 *     upper bound that fits within MySQL's default row-size budget
 *     even for multi-byte charsets.
 *   - `uuid` → `varchar({ length: 36 })`. MySQL has no native UUID
 *     column; 36 characters is the canonical hyphenated form.
 *   - `datetime` → `datetime('col', { fsp: 3 })`. Triad datetimes are
 *     ISO-8601 strings that may include fractional seconds, so we
 *     choose `datetime` over `timestamp`: `timestamp` is limited to
 *     2038 and performs implicit timezone conversions, whereas
 *     `datetime` stores the wall-clock value verbatim. `fsp: 3` keeps
 *     millisecond precision, matching the JS `Date().toISOString()`
 *     shape used elsewhere in Triad codegen.
 *   - `bigint` → `bigint('col', { mode: 'number' })`. Triad's int64
 *     has a TypeScript output type of `number` (not `bigint`), so we
 *     ask Drizzle to return JS numbers. Values outside
 *     `Number.MAX_SAFE_INTEGER` could lose precision; projects that
 *     need full 64-bit fidelity should set `mode: 'bigint'` manually
 *     after regeneration.
 *   - `enum` → `mysqlEnum('col', [...values] as const)`. MySQL has a
 *     real ENUM type and Drizzle exposes it; we use it instead of
 *     emulating with a text-plus-constraint like Postgres.
 *   - `json` → `json`. Available in MySQL 5.7+ which is the floor we
 *     target.
 */
const MYSQL: DialectProfile = {
  dialect: 'mysql',
  importModule: 'drizzle-orm/mysql-core',
  tableHelper: 'mysqlTable',
  columnHelper: (column) => {
    switch (column.logicalType) {
      case 'string':
      case 'uuid':
        return 'varchar';
      case 'datetime':
        return 'datetime';
      case 'enum':
        return 'mysqlEnum';
      case 'integer':
        return 'int';
      case 'bigint':
        return 'bigint';
      case 'float':
        return 'float';
      case 'double':
        return 'double';
      case 'boolean':
        return 'boolean';
      case 'json':
        return 'json';
    }
  },
  columnOptions: (column) => {
    if (column.logicalType === 'uuid') {
      return '{ length: 36 }';
    }
    if (column.logicalType === 'string') {
      // Honour an explicit .maxLength(n); otherwise default to 255.
      const length = column.maxLength ?? 255;
      return `{ length: ${length} }`;
    }
    if (column.logicalType === 'datetime') {
      // fsp: 3 keeps millisecond precision to match ISO-8601 strings.
      return '{ fsp: 3 }';
    }
    if (column.logicalType === 'bigint') {
      // Return JS numbers rather than BigInts — matches Triad's int64,
      // whose TypeScript output type is `number`.
      return "{ mode: 'number' }";
    }
    if (column.logicalType === 'enum' && column.enumValues) {
      // mysqlEnum takes a tuple as its second positional argument, not
      // an options object. Emitting `as const` preserves the literal
      // type so Drizzle's output type is a narrow union.
      const values = column.enumValues.map((v) => `'${v}'`).join(', ');
      return `[${values}] as const`;
    }
    return undefined;
  },
};

function profileFor(dialect: Dialect): DialectProfile {
  switch (dialect) {
    case 'sqlite':
      return SQLITE;
    case 'postgres':
      return POSTGRES;
    case 'mysql':
      return MYSQL;
  }
}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

export function emitSqlite(
  tables: readonly TableDescriptor[],
  options: EmitOptions = {},
): string {
  return emitWithDialect(SQLITE, tables, options);
}

export function emitPostgres(
  tables: readonly TableDescriptor[],
  options: EmitOptions = {},
): string {
  return emitWithDialect(POSTGRES, tables, options);
}

export function emitMysql(
  tables: readonly TableDescriptor[],
  options: EmitOptions = {},
): string {
  return emitWithDialect(MYSQL, tables, options);
}

export function emitForDialect(
  dialect: Dialect,
  tables: readonly TableDescriptor[],
  options: EmitOptions = {},
): string {
  return emitWithDialect(profileFor(dialect), tables, options);
}

// ---------------------------------------------------------------------------
// Core emission
// ---------------------------------------------------------------------------

function emitWithDialect(
  profile: DialectProfile,
  tables: readonly TableDescriptor[],
  options: EmitOptions,
): string {
  const header = buildHeader(profile.dialect, options);
  const imports = buildImports(profile, tables);
  const tableSources = tables
    .map((table) => emitTable(profile, table))
    .join('\n\n');
  return `${header}\n${imports}\n\n${tableSources}\n`;
}

function buildImports(
  profile: DialectProfile,
  tables: readonly TableDescriptor[],
): string {
  const helpers = new Set<string>([profile.tableHelper]);
  for (const table of tables) {
    for (const column of table.columns) {
      helpers.add(profile.columnHelper(column));
    }
  }
  // tableHelper first, then the column helpers alphabetically for
  // deterministic output.
  const columnHelpers = [...helpers]
    .filter((h) => h !== profile.tableHelper)
    .sort();
  const ordered = [profile.tableHelper, ...columnHelpers];
  return `import { ${ordered.join(', ')} } from '${profile.importModule}';`;
}

function emitTable(profile: DialectProfile, table: TableDescriptor): string {
  const lines: string[] = [];
  lines.push(`/** Storage for the \`${table.modelName}\` Triad model. */`);
  lines.push(
    `export const ${table.identifier} = ${profile.tableHelper}('${table.tableName}', {`,
  );
  for (const column of table.columns) {
    if (column.comment) {
      lines.push(`  // ${column.comment}`);
    }
    lines.push(`  ${emitColumn(profile, column)},`);
  }
  lines.push('});');
  return lines.join('\n');
}

function emitColumn(
  profile: DialectProfile,
  column: ColumnDescriptor,
): string {
  const helper = profile.columnHelper(column);
  const options = profile.columnOptions(column);
  const args: string[] = [`'${column.columnName}'`];
  if (options) args.push(options);

  let expr = `${column.fieldName}: ${helper}(${args.join(', ')})`;

  const chain: string[] = [];
  if (column.references) {
    const [tableRef, colRef] = column.references.split('.');
    if (tableRef && colRef) {
      chain.push(`references(() => ${tableRef}.${colRef})`);
    }
  }
  if (column.notNull) chain.push('notNull()');
  if (column.primaryKey) chain.push('primaryKey()');
  if (column.unique) chain.push('unique()');

  if (column.default) {
    switch (column.default.kind) {
      case 'literal':
        chain.push(`default(${jsLiteral(column.default.value)})`);
        break;
      case 'now':
        chain.push('$defaultFn(() => new Date().toISOString())');
        break;
      case 'random':
        chain.push('$defaultFn(() => crypto.randomUUID())');
        break;
    }
  }

  if (chain.length > 0) {
    expr += '.' + chain.join('.');
  }
  return expr;
}

function jsLiteral(value: string | number | boolean | null): string {
  if (value === null) return 'null';
  if (typeof value === 'string') {
    return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  }
  return String(value);
}
