/**
 * Per-channel code emitter.
 *
 * Given a single Triad `Channel` and a shared `TypeEmitter`, produce
 * the TypeScript source for its dedicated client file. Named schemas
 * encountered while walking the channel's shapes are registered on
 * the emitter; the generator then writes every registered interface
 * into `types.ts` at the top level.
 */

import type { Channel, SchemaNode } from '@triadjs/core';
import { TypeEmitter } from '@triadjs/tanstack-query';

export interface EmittedChannel {
  /** File path (relative to outputDir). */
  path: string;
  /** Source contents. */
  contents: string;
  /** PascalCase base name (e.g. `BookReviews`). */
  baseName: string;
  /** Named type references the file imports from `./types.js`. */
  typeImports: string[];
}

function toPascalCase(name: string): string {
  return name
    .replace(/[_-]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function toKebabCase(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}

interface ShapeField {
  name: string;
  type: string;
  optional: boolean;
}

function emitInlineShape(
  emitter: TypeEmitter,
  model:
    | {
        readonly shape?: Record<string, SchemaNode>;
      }
    | undefined,
  typeImports: Set<string>,
): ShapeField[] {
  if (!model || !model.shape) return [];
  const fields: ShapeField[] = [];
  for (const [fieldName, fieldSchema] of Object.entries(model.shape)) {
    const typeStr = emitter.emitType(fieldSchema);
    collectTypeRefs(typeStr, typeImports);
    fields.push({
      name: fieldName,
      type: typeStr,
      optional: fieldSchema.isOptional === true,
    });
  }
  return fields;
}

const TYPE_REF_RE = /\b([A-Z][A-Za-z0-9_]*)\b/g;
const BUILTIN = new Set([
  'Array',
  'Record',
  'Partial',
  'Readonly',
  'ReadonlyArray',
  'Promise',
  'Map',
  'Set',
  'Date',
  'Buffer',
  'Uint8Array',
  'ArrayBuffer',
]);

function collectTypeRefs(type: string, out: Set<string>): void {
  let match: RegExpExecArray | null;
  TYPE_REF_RE.lastIndex = 0;
  while ((match = TYPE_REF_RE.exec(type)) !== null) {
    const ref = match[1]!;
    if (!BUILTIN.has(ref)) out.add(ref);
  }
}

function formatFieldLines(fields: ShapeField[], indent: string): string[] {
  return fields.map(
    (f) => `${indent}${safeKey(f.name)}${f.optional ? '?' : ''}: ${f.type};`,
  );
}

const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
function safeKey(key: string): string {
  return IDENT_RE.test(key) ? key : JSON.stringify(key);
}

/**
 * Turn a channel path like `/ws/books/:bookId/reviews` into a
 * JavaScript template expression that interpolates the typed
 * `params` object:
 *
 * ```ts
 * `/ws/books/${encodeURIComponent(params.bookId)}/reviews`
 * ```
 */
function renderPathTemplate(path: string): string {
  const parts = path.split('/');
  const pieces: string[] = [];
  for (const part of parts) {
    if (part.startsWith(':')) {
      const name = part.slice(1);
      pieces.push('${encodeURIComponent(String(params.' + name + '))}');
    } else {
      pieces.push(part);
    }
  }
  return '`' + pieces.join('/') + '`';
}

export function emitChannelClient(
  channel: Channel,
  emitter: TypeEmitter,
): EmittedChannel {
  const baseName = toPascalCase(channel.name);
  const typeImports = new Set<string>();

  // ---- Connection shapes --------------------------------------------------
  const params = emitInlineShape(emitter, channel.connection.params, typeImports);
  const query = emitInlineShape(emitter, channel.connection.query, typeImports);
  const headers = emitInlineShape(
    emitter,
    channel.connection.headers,
    typeImports,
  );

  // ---- Message payload types ---------------------------------------------
  interface MsgRef {
    type: string;
    tsType: string;
    description: string;
  }
  const clientMessages: MsgRef[] = [];
  for (const [type, config] of Object.entries(channel.clientMessages)) {
    const tsType = emitter.emitType(config.schema);
    collectTypeRefs(tsType, typeImports);
    clientMessages.push({ type, tsType, description: config.description });
  }
  const serverMessages: MsgRef[] = [];
  for (const [type, config] of Object.entries(channel.serverMessages)) {
    const tsType = emitter.emitType(config.schema);
    collectTypeRefs(tsType, typeImports);
    serverMessages.push({ type, tsType, description: config.description });
  }

  // ---- Emit ---------------------------------------------------------------
  const lines: string[] = [];
  lines.push('// Generated by @triadjs/channel-client — do not edit.');
  lines.push(
    '// Regenerate with: triad frontend generate --target channel-client',
  );
  lines.push('');
  lines.push(
    "import { BaseChannelClient, type AuthStrategy, type BaseChannelClientOptions, type ChannelCloseEvent, type ChannelState, type ReconnectOptions } from './client.js';",
  );
  if (typeImports.size > 0) {
    const sorted = Array.from(typeImports).sort();
    lines.push(`import type { ${sorted.join(', ')} } from './types.js';`);
  }
  lines.push('');

  // Params interface
  lines.push(`export interface ${baseName}ConnectionParams {`);
  lines.push(...formatFieldLines(params, '  '));
  lines.push('}');
  lines.push('');

  // Query interface (may be empty)
  lines.push(`export interface ${baseName}Query {`);
  lines.push(...formatFieldLines(query, '  '));
  lines.push('}');
  lines.push('');

  // Headers interface
  lines.push(`export interface ${baseName}Headers {`);
  lines.push(...formatFieldLines(headers, '  '));
  lines.push('}');
  lines.push('');

  // Options
  lines.push(`export interface ${baseName}ClientOptions {`);
  lines.push('  /** Absolute origin URL, e.g. \'wss://api.example.com\'. */');
  lines.push('  url: string;');
  lines.push(`  params: ${baseName}ConnectionParams;`);
  lines.push(`  query?: ${baseName}Query;`);
  lines.push(`  headers?: Partial<${baseName}Headers>;`);
  lines.push('  auth?: AuthStrategy;');
  lines.push('  token?: string;');
  lines.push('  firstMessageType?: string;');
  lines.push('  firstMessagePayload?: unknown;');
  lines.push('  reconnect?: ReconnectOptions;');
  lines.push('  WebSocketImpl?: BaseChannelClientOptions[\'WebSocketImpl\'];');
  lines.push('}');
  lines.push('');

  // Send map type
  if (clientMessages.length > 0) {
    lines.push(`export interface ${baseName}SendMap {`);
    for (const m of clientMessages) {
      if (m.description) lines.push(`  /** ${m.description.replace(/\*\//g, '*\\/')} */`);
      lines.push(`  ${safeKey(m.type)}(payload: ${m.tsType}): void;`);
    }
    lines.push('}');
    lines.push('');
  }

  // Event union type for typed `on`
  if (serverMessages.length > 0) {
    lines.push(`export type ${baseName}ServerEvent =`);
    for (let i = 0; i < serverMessages.length; i += 1) {
      const m = serverMessages[i]!;
      const prefix = i === 0 ? '  |' : '  |';
      lines.push(
        `${prefix} { readonly type: ${JSON.stringify(m.type)}; readonly data: ${m.tsType} }`,
      );
    }
    lines.push(';');
    lines.push('');
  }

  // Client interface with overloaded `on`. Lifecycle events (`open`,
  // `close`, `stateChange`, `error`) are emitted only when the channel
  // hasn't declared a server message of the same name — domain
  // messages always win, because they're the ones users care about
  // when they write `on('error', ...)`.
  const serverMessageNames = new Set(serverMessages.map((m) => m.type));
  const LIFECYCLE_EVENTS: Array<[string, string]> = [
    ['stateChange', '(state: ChannelState) => void'],
    ['open', '() => void'],
    ['close', '(event: ChannelCloseEvent) => void'],
    ['error', '(error: unknown) => void'],
  ];

  lines.push(`export interface ${baseName}Client {`);
  lines.push('  readonly state: ChannelState;');
  if (clientMessages.length > 0) {
    lines.push(`  readonly send: ${baseName}SendMap;`);
  }
  for (const m of serverMessages) {
    lines.push(
      `  on(event: ${JSON.stringify(m.type)}, cb: (payload: ${m.tsType}) => void): () => void;`,
    );
  }
  for (const [event, cbType] of LIFECYCLE_EVENTS) {
    if (serverMessageNames.has(event)) continue;
    lines.push(`  on(event: '${event}', cb: ${cbType}): () => void;`);
  }
  lines.push('  close(): Promise<void>;');
  lines.push('}');
  lines.push('');

  // Factory function
  const pathExpr = renderPathTemplate(channel.path);
  lines.push(
    `export function create${baseName}Client(options: ${baseName}ClientOptions): ${baseName}Client {`,
  );
  lines.push('  const { params } = options;');
  lines.push('  void params;');
  lines.push(`  const path = ${pathExpr};`);
  lines.push('  const baseUrl = options.url.replace(/\\/$/, \'\');');
  lines.push('  const wsUrl = baseUrl + path;');
  lines.push('  const base = new BaseChannelClient({');
  lines.push('    url: wsUrl,');
  lines.push('    query: options.query as Record<string, string | number | boolean | undefined> | undefined,');
  lines.push('    headers: options.headers as Record<string, string> | undefined,');
  lines.push('    auth: options.auth,');
  lines.push('    token: options.token,');
  lines.push('    firstMessageType: options.firstMessageType,');
  lines.push('    firstMessagePayload: options.firstMessagePayload,');
  lines.push('    reconnect: options.reconnect,');
  lines.push('    WebSocketImpl: options.WebSocketImpl,');
  lines.push('  });');
  lines.push('');

  if (clientMessages.length > 0) {
    lines.push(`  const send: ${baseName}SendMap = {`);
    for (const m of clientMessages) {
      lines.push(
        `    ${safeKey(m.type)}(payload: ${m.tsType}): void { base.send(${JSON.stringify(m.type)}, payload); },`,
      );
    }
    lines.push('  };');
    lines.push('');
  }

  // Generate a stable set of known message types at emit time so the
  // dispatcher can tell them apart from lifecycle event names.
  const messageTypesLiteral = JSON.stringify(serverMessages.map((m) => m.type));
  lines.push(
    `  const __messageTypes = new Set<string>(${messageTypesLiteral});`,
  );
  lines.push('  function on(event: string, cb: (arg: never) => void): () => void {');
  lines.push('    if (__messageTypes.has(event)) return base.onMessage(event, cb as (payload: unknown) => void);');
  lines.push("    if (event === 'stateChange') return base.onStateChange(cb as (s: ChannelState) => void);");
  lines.push("    if (event === 'open') return base.onOpen(cb as () => void);");
  lines.push("    if (event === 'close') return base.onClose(cb as (e: ChannelCloseEvent) => void);");
  lines.push("    if (event === 'error') return base.onError(cb as (err: unknown) => void);");
  lines.push('    return base.onMessage(event, cb as (payload: unknown) => void);');
  lines.push('  }');
  lines.push('');

  lines.push('  return {');
  lines.push('    get state(): ChannelState { return base.state; },');
  if (clientMessages.length > 0) {
    lines.push('    send,');
  }
  lines.push(`    on: on as ${baseName}Client['on'],`);
  lines.push('    close(): Promise<void> { return base.close(); },');
  lines.push('  };');
  lines.push('}');
  lines.push('');

  return {
    path: `${toKebabCase(channel.name)}.ts`,
    contents: lines.join('\n'),
    baseName,
    typeImports: Array.from(typeImports),
  };
}
