/**
 * Runtime client template.
 *
 * This module exports a single string `CLIENT_RUNTIME_SOURCE`
 * containing the vanilla TypeScript WebSocket wrapper that every
 * per-channel client factory extends. It is emitted verbatim into
 * the user's output directory as `client.ts`.
 *
 * Why a string and not a real source file we copy? Keeping it inline
 * lets the generator ship as a single published package without
 * relying on `files`/`bin` tricks, and lets us substitute the
 * default base URL into the output cleanly.
 */

export interface ClientTemplateOptions {
  /** Default base URL used when constructing channel clients. */
  baseUrl: string;
}

export function renderClientRuntime(options: ClientTemplateOptions): string {
  const baseUrl = JSON.stringify(options.baseUrl);
  return `// Generated by @triadjs/channel-client — do not edit.
// Regenerate with: triad frontend generate --target channel-client

/**
 * Runtime WebSocket client for Triad channels.
 *
 * This file is a small, dependency-free wrapper over the browser
 * \`WebSocket\` global (polyfillable in Node via the \`ws\` package,
 * which exposes the same API). Generated per-channel clients in the
 * same directory extend this base with typed send/on methods.
 */

export const DEFAULT_BASE_URL = ${baseUrl};

export type ChannelState =
  | 'connecting'
  | 'open'
  | 'closed'
  | 'reconnecting';

export type AuthStrategy =
  | 'subprotocol'
  | 'query'
  | 'first-message'
  | 'header';

export interface ReconnectOptions {
  enabled?: boolean;
  maxAttempts?: number;
  initialDelayMs?: number;
  maxDelayMs?: number;
  factor?: number;
  jitter?: boolean;
}

export interface BaseChannelClientOptions {
  /** Absolute WebSocket URL (e.g. ws://host/ws/rooms/abc). */
  url: string;
  /**
   * Optional query string parameters appended to \`url\`. Values are
   * URL-encoded. Use this for \`query\`-based auth strategies too.
   */
  query?: Record<string, string | number | boolean | undefined>;
  /**
   * Optional headers. Only honored in Node clients (browser
   * WebSocket does not support custom headers on the handshake).
   */
  headers?: Record<string, string>;
  /**
   * Auth strategy for this connection. Defaults to \`'first-message'\`
   * because it's the only strategy that works uniformly across
   * browsers and Node clients.
   */
  auth?: AuthStrategy;
  /** Auth token (or any string) used by the selected strategy. */
  token?: string;
  /** First-message auth type. Defaults to \`'__auth'\`. */
  firstMessageType?: string;
  /** First-message auth payload. Defaults to \`{ token }\`. */
  firstMessagePayload?: unknown;
  /** Reconnection behavior. */
  reconnect?: ReconnectOptions;
  /**
   * Injected WebSocket constructor. Defaults to the global. Set to
   * the \`ws\` package's \`WebSocket\` to run in Node without a DOM.
   */
  WebSocketImpl?: typeof WebSocket;
  /**
   * When \`true\`, this client joins a module-level shared connection
   * pool keyed by \`(url, query, headers, auth, token)\`. Multiple
   * clients with the same key share one underlying WebSocket; a
   * reference count tracks live subscribers, and the socket is torn
   * down (after \`sharedCloseDelayMs\`) when the last subscriber
   * leaves.
   *
   * Default: \`false\`. Opt in per-instance.
   *
   * Interacts with \`queueOfflineSends\`: when both are set, the
   * queue lives on the pool entry, so every subscriber contributes
   * to the same FIFO and messages are flushed once when the shared
   * socket opens.
   */
  shared?: boolean;
  /**
   * Grace period (ms) between the last shared subscriber leaving
   * and the underlying socket being closed. If a new subscriber
   * joins within the window, teardown is cancelled. Only meaningful
   * when \`shared: true\`.
   *
   * Default: \`1000\`. Set to \`0\` to close immediately.
   */
  sharedCloseDelayMs?: number;
  /**
   * Buffer sends that occur while the socket is not \`'open'\`. When
   * the connection transitions to \`'open'\`, queued messages flush
   * in FIFO order. Useful for UI code that wants fire-and-forget
   * sends without state checks.
   *
   * Default: \`false\`. When disabled, calling \`send()\` before the
   * socket is open throws (existing behavior).
   *
   * Note: \`close()\` does NOT drain the queue — explicitly-closed
   * clients drop any unflushed messages.
   */
  queueOfflineSends?: boolean;
  /**
   * Maximum number of buffered messages when \`queueOfflineSends\`
   * is enabled. When a send would exceed the limit, the OLDEST
   * queued message is dropped (drop-oldest FIFO) and
   * \`onQueueDropped\` is invoked for it.
   *
   * Default: \`100\`.
   */
  maxQueueSize?: number;
  /**
   * Callback invoked with each message dropped due to
   * \`maxQueueSize\` overflow. Useful for telemetry or surfacing a
   * user-facing warning.
   */
  onQueueDropped?: (dropped: { type: string; payload: unknown }) => void;
}

export interface ChannelEnvelope {
  type: string;
  data: unknown;
}

export interface ChannelCloseEvent {
  code: number;
  reason: string;
}

type Listener<T> = (arg: T) => void;

interface QueuedSend {
  type: string;
  payload: unknown;
}

interface CoreListeners {
  messages: Map<string, Set<Listener<unknown>>>;
  states: Set<Listener<ChannelState>>;
  opens: Set<Listener<void>>;
  closes: Set<Listener<ChannelCloseEvent>>;
  errors: Set<Listener<unknown>>;
}

function newCoreListeners(): CoreListeners {
  return {
    messages: new Map(),
    states: new Set(),
    opens: new Set(),
    closes: new Set(),
    errors: new Set(),
  };
}

/**
 * \`ConnectionCore\` owns the underlying WebSocket, connection state,
 * reconnect loop, and (optionally) an offline send queue. A core
 * can be shared across multiple \`BaseChannelClient\` instances
 * (ref-counted via the module-level pool) or owned exclusively by
 * a single client.
 */
class ConnectionCore {
  readonly options: BaseChannelClientOptions;
  socket: WebSocket | undefined;
  state: ChannelState = 'connecting';
  readonly subscribers = new Set<CoreListeners>();
  attempts = 0;
  explicitClose = false;
  refCount = 0;
  closeTimer: ReturnType<typeof setTimeout> | undefined;
  readonly queueEnabled: boolean;
  readonly maxQueueSize: number;
  readonly onQueueDropped?: (d: QueuedSend) => void;
  queue: QueuedSend[] = [];
  poolKey: string | undefined;

  constructor(options: BaseChannelClientOptions) {
    this.options = options;
    this.queueEnabled = options.queueOfflineSends === true;
    this.maxQueueSize = options.maxQueueSize ?? 100;
    this.onQueueDropped = options.onQueueDropped;
  }

  addSubscriber(listeners: CoreListeners): void {
    this.subscribers.add(listeners);
  }

  removeSubscriber(listeners: CoreListeners): void {
    this.subscribers.delete(listeners);
  }

  setState(next: ChannelState): void {
    if (this.state === next) return;
    this.state = next;
    for (const l of this.subscribers) {
      for (const cb of l.states) cb(next);
    }
    if (next === 'open') this.flushQueue();
  }

  flushQueue(): void {
    if (!this.queueEnabled) return;
    const sock = this.socket;
    if (!sock || sock.readyState !== 1) return;
    const pending = this.queue;
    this.queue = [];
    for (const item of pending) {
      sock.send(JSON.stringify({ type: item.type, data: item.payload }));
    }
  }

  enqueueOrSend(type: string, payload: unknown): void {
    const sock = this.socket;
    if (sock && sock.readyState === 1 && this.state === 'open') {
      sock.send(JSON.stringify({ type, data: payload }));
      return;
    }
    if (!this.queueEnabled) {
      throw new Error(
        'Cannot send on a channel that is not open (state=' + this.state + ')',
      );
    }
    if (this.queue.length >= this.maxQueueSize) {
      const dropped = this.queue.shift();
      if (dropped && this.onQueueDropped) this.onQueueDropped(dropped);
    }
    this.queue.push({ type, payload });
  }

  dispatchMessage(envelope: ChannelEnvelope): void {
    for (const l of this.subscribers) {
      const set = l.messages.get(envelope.type);
      if (!set) continue;
      for (const cb of set) cb(envelope.data);
    }
  }

  dispatchOpen(): void {
    for (const l of this.subscribers) {
      for (const cb of l.opens) cb();
    }
  }

  dispatchClose(info: ChannelCloseEvent): void {
    for (const l of this.subscribers) {
      for (const cb of l.closes) cb(info);
    }
  }

  dispatchError(err: unknown): void {
    for (const l of this.subscribers) {
      for (const cb of l.errors) cb(err);
    }
  }

  connect(): void {
    const url = buildUrl(this.options);
    const Impl =
      this.options.WebSocketImpl ??
      (typeof WebSocket !== 'undefined' ? WebSocket : undefined);
    if (!Impl) {
      throw new Error(
        'No WebSocket implementation available. Pass options.WebSocketImpl.',
      );
    }

    this.setState(this.attempts === 0 ? 'connecting' : 'reconnecting');

    const subprotocols: string[] = [];
    if (this.options.auth === 'subprotocol' && this.options.token !== undefined) {
      subprotocols.push('bearer', this.options.token);
    }

    const sock =
      subprotocols.length > 0
        ? new Impl(url, subprotocols)
        : new Impl(url);
    this.socket = sock;

    sock.addEventListener('open', () => {
      this.attempts = 0;
      if (this.options.auth === 'first-message') {
        const type = this.options.firstMessageType ?? '__auth';
        const payload =
          this.options.firstMessagePayload !== undefined
            ? this.options.firstMessagePayload
            : { token: this.options.token };
        try {
          sock.send(JSON.stringify({ type, data: payload }));
        } catch (err) {
          this.dispatchError(err);
        }
      }
      this.setState('open');
      this.dispatchOpen();
    });

    sock.addEventListener('message', (event: MessageEvent) => {
      let envelope: ChannelEnvelope;
      try {
        const text =
          typeof event.data === 'string'
            ? event.data
            : event.data instanceof ArrayBuffer
              ? new TextDecoder().decode(event.data)
              : String(event.data);
        envelope = JSON.parse(text) as ChannelEnvelope;
      } catch (err) {
        this.dispatchError(err);
        return;
      }
      if (typeof envelope !== 'object' || envelope === null) return;
      this.dispatchMessage(envelope);
    });

    sock.addEventListener('error', (event: Event) => {
      this.dispatchError(event);
    });

    sock.addEventListener('close', (event: CloseEvent) => {
      const closeInfo: ChannelCloseEvent = {
        code: event.code,
        reason: event.reason,
      };
      this.dispatchClose(closeInfo);
      if (this.explicitClose) {
        this.setState('closed');
        return;
      }
      const rc = this.options.reconnect;
      if (!rc || rc.enabled === false) {
        this.setState('closed');
        return;
      }
      const maxAttempts = rc.maxAttempts ?? 5;
      if (this.attempts >= maxAttempts) {
        this.setState('closed');
        return;
      }
      this.attempts += 1;
      const initial = rc.initialDelayMs ?? 500;
      const factor = rc.factor ?? 2;
      const max = rc.maxDelayMs ?? 10_000;
      const base = Math.min(max, initial * Math.pow(factor, this.attempts - 1));
      const delay = jitterDelay(base, rc.jitter ?? true);
      this.setState('reconnecting');
      setTimeout(() => {
        if (this.explicitClose) return;
        this.connect();
      }, delay);
    });
  }

  teardown(): void {
    this.explicitClose = true;
    const sock = this.socket;
    if (!sock) return;
    if (sock.readyState === 3) return;
    try {
      sock.close();
    } catch {
      /* ignore */
    }
  }
}

/**
 * Module-level shared connection pool. Keyed by a stable
 * serialization of the connection descriptor. Tests can retrieve
 * this via \`__internals.getPool()\`.
 */
class ConnectionPool {
  private readonly entries = new Map<string, ConnectionCore>();

  size(): number {
    return this.entries.size;
  }

  acquire(key: string, options: BaseChannelClientOptions): ConnectionCore {
    let core = this.entries.get(key);
    if (core) {
      if (core.closeTimer !== undefined) {
        clearTimeout(core.closeTimer);
        core.closeTimer = undefined;
      }
      core.refCount += 1;
      return core;
    }
    core = new ConnectionCore(options);
    core.poolKey = key;
    core.refCount = 1;
    this.entries.set(key, core);
    core.connect();
    return core;
  }

  release(core: ConnectionCore): void {
    if (core.poolKey === undefined) return;
    core.refCount -= 1;
    if (core.refCount > 0) return;
    const delay = core.options.sharedCloseDelayMs ?? 1000;
    const finalize = () => {
      core.closeTimer = undefined;
      if (core.refCount > 0) return;
      if (core.poolKey !== undefined) this.entries.delete(core.poolKey);
      core.teardown();
    };
    if (delay <= 0) {
      finalize();
      return;
    }
    core.closeTimer = setTimeout(finalize, delay);
  }
}

const __pool = new ConnectionPool();

export const __internals = {
  getPool(): ConnectionPool {
    return __pool;
  },
};

function poolKey(options: BaseChannelClientOptions): string {
  return JSON.stringify({
    url: options.url,
    query: options.query ?? null,
    headers: options.headers ?? null,
    auth: options.auth ?? null,
    token: options.token ?? null,
  });
}

function buildUrl(options: BaseChannelClientOptions): string {
  let url = options.url;
  const query: Record<string, string> = {};
  if (options.query) {
    for (const [key, value] of Object.entries(options.query)) {
      if (value === undefined) continue;
      query[key] = String(value);
    }
  }
  if (options.auth === 'query' && options.token !== undefined) {
    query['token'] = options.token;
  }
  const entries = Object.entries(query);
  if (entries.length > 0) {
    const qs = entries
      .map(([k, v]) => encodeURIComponent(k) + '=' + encodeURIComponent(v))
      .join('&');
    url += (url.includes('?') ? '&' : '?') + qs;
  }
  return url;
}

function jitterDelay(base: number, jitter: boolean): number {
  if (!jitter) return base;
  const j = 0.5 + Math.random();
  return Math.round(base * j);
}

/**
 * Base WebSocket wrapper used by all generated channel clients.
 * Consumers usually do not instantiate this directly — the per-
 * channel \`create*Client\` factories do the typed wiring.
 */
export class BaseChannelClient {
  private readonly core: ConnectionCore;
  private readonly listeners: CoreListeners = newCoreListeners();
  private readonly isShared: boolean;
  private released = false;

  constructor(options: BaseChannelClientOptions) {
    this.isShared = options.shared === true;
    if (this.isShared) {
      this.core = __pool.acquire(poolKey(options), options);
    } else {
      this.core = new ConnectionCore(options);
      this.core.refCount = 1;
      this.core.connect();
    }
    this.core.addSubscriber(this.listeners);
  }

  get state(): ChannelState {
    return this.core.state;
  }

  send(type: string, payload: unknown): void {
    this.core.enqueueOrSend(type, payload);
  }

  onMessage(type: string, cb: Listener<unknown>): () => void {
    let set = this.listeners.messages.get(type);
    if (!set) {
      set = new Set();
      this.listeners.messages.set(type, set);
    }
    set.add(cb);
    return () => {
      set!.delete(cb);
    };
  }

  onStateChange(cb: Listener<ChannelState>): () => void {
    this.listeners.states.add(cb);
    return () => {
      this.listeners.states.delete(cb);
    };
  }

  onOpen(cb: Listener<void>): () => void {
    this.listeners.opens.add(cb);
    return () => {
      this.listeners.opens.delete(cb);
    };
  }

  onClose(cb: Listener<ChannelCloseEvent>): () => void {
    this.listeners.closes.add(cb);
    return () => {
      this.listeners.closes.delete(cb);
    };
  }

  onError(cb: Listener<unknown>): () => void {
    this.listeners.errors.add(cb);
    return () => {
      this.listeners.errors.delete(cb);
    };
  }

  async close(): Promise<void> {
    if (this.released) return;
    this.released = true;
    this.core.removeSubscriber(this.listeners);
    if (this.isShared) {
      __pool.release(this.core);
      return;
    }
    // Drop the queue on explicit close. Exclusive cores are torn
    // down immediately.
    this.core.queue = [];
    const sock = this.core.socket;
    this.core.explicitClose = true;
    if (!sock) return;
    if (sock.readyState === 3) return;
    await new Promise<void>((resolve) => {
      sock.addEventListener('close', () => resolve(), { once: true });
      try {
        sock.close();
      } catch {
        resolve();
      }
    });
  }
}
`;
}
