/**
 * Runtime client template.
 *
 * This module exports a single string `CLIENT_RUNTIME_SOURCE`
 * containing the vanilla TypeScript WebSocket wrapper that every
 * per-channel client factory extends. It is emitted verbatim into
 * the user's output directory as `client.ts`.
 *
 * Why a string and not a real source file we copy? Keeping it inline
 * lets the generator ship as a single published package without
 * relying on `files`/`bin` tricks, and lets us substitute the
 * default base URL into the output cleanly.
 */

export interface ClientTemplateOptions {
  /** Default base URL used when constructing channel clients. */
  baseUrl: string;
}

export function renderClientRuntime(options: ClientTemplateOptions): string {
  const baseUrl = JSON.stringify(options.baseUrl);
  return `// Generated by @triad/channel-client — do not edit.
// Regenerate with: triad frontend generate --target channel-client

/**
 * Runtime WebSocket client for Triad channels.
 *
 * This file is a small, dependency-free wrapper over the browser
 * \`WebSocket\` global (polyfillable in Node via the \`ws\` package,
 * which exposes the same API). Generated per-channel clients in the
 * same directory extend this base with typed send/on methods.
 */

export const DEFAULT_BASE_URL = ${baseUrl};

export type ChannelState =
  | 'connecting'
  | 'open'
  | 'closed'
  | 'reconnecting';

export type AuthStrategy =
  | 'subprotocol'
  | 'query'
  | 'first-message'
  | 'header';

export interface ReconnectOptions {
  enabled?: boolean;
  maxAttempts?: number;
  initialDelayMs?: number;
  maxDelayMs?: number;
  factor?: number;
  jitter?: boolean;
}

export interface BaseChannelClientOptions {
  /** Absolute WebSocket URL (e.g. ws://host/ws/rooms/abc). */
  url: string;
  /**
   * Optional query string parameters appended to \`url\`. Values are
   * URL-encoded. Use this for \`query\`-based auth strategies too.
   */
  query?: Record<string, string | number | boolean | undefined>;
  /**
   * Optional headers. Only honored in Node clients (browser
   * WebSocket does not support custom headers on the handshake).
   */
  headers?: Record<string, string>;
  /**
   * Auth strategy for this connection. Defaults to \`'first-message'\`
   * because it's the only strategy that works uniformly across
   * browsers and Node clients.
   */
  auth?: AuthStrategy;
  /** Auth token (or any string) used by the selected strategy. */
  token?: string;
  /** First-message auth type. Defaults to \`'__auth'\`. */
  firstMessageType?: string;
  /** First-message auth payload. Defaults to \`{ token }\`. */
  firstMessagePayload?: unknown;
  /** Reconnection behavior. */
  reconnect?: ReconnectOptions;
  /**
   * Injected WebSocket constructor. Defaults to the global. Set to
   * the \`ws\` package's \`WebSocket\` to run in Node without a DOM.
   */
  WebSocketImpl?: typeof WebSocket;
}

export interface ChannelEnvelope {
  type: string;
  data: unknown;
}

export interface ChannelCloseEvent {
  code: number;
  reason: string;
}

type Listener<T> = (arg: T) => void;

function buildUrl(options: BaseChannelClientOptions): string {
  let url = options.url;
  const query: Record<string, string> = {};
  if (options.query) {
    for (const [key, value] of Object.entries(options.query)) {
      if (value === undefined) continue;
      query[key] = String(value);
    }
  }
  if (options.auth === 'query' && options.token !== undefined) {
    query['token'] = options.token;
  }
  const entries = Object.entries(query);
  if (entries.length > 0) {
    const qs = entries
      .map(([k, v]) => encodeURIComponent(k) + '=' + encodeURIComponent(v))
      .join('&');
    url += (url.includes('?') ? '&' : '?') + qs;
  }
  return url;
}

function jitterDelay(base: number, jitter: boolean): number {
  if (!jitter) return base;
  const j = 0.5 + Math.random();
  return Math.round(base * j);
}

/**
 * Base WebSocket wrapper used by all generated channel clients.
 * Consumers usually do not instantiate this directly — the per-
 * channel \`create*Client\` factories do the typed wiring.
 */
export class BaseChannelClient {
  private readonly options: BaseChannelClientOptions;
  private socket: WebSocket | undefined;
  private _state: ChannelState = 'connecting';
  private readonly messageListeners = new Map<
    string,
    Set<Listener<unknown>>
  >();
  private readonly stateListeners = new Set<Listener<ChannelState>>();
  private readonly openListeners = new Set<Listener<void>>();
  private readonly closeListeners = new Set<Listener<ChannelCloseEvent>>();
  private readonly errorListeners = new Set<Listener<unknown>>();
  private attempts = 0;
  private explicitClose = false;

  constructor(options: BaseChannelClientOptions) {
    this.options = options;
    this.connect();
  }

  get state(): ChannelState {
    return this._state;
  }

  send(type: string, payload: unknown): void {
    const sock = this.socket;
    if (!sock || sock.readyState !== 1) {
      throw new Error(
        'Cannot send on a channel that is not open (state=' + this._state + ')',
      );
    }
    sock.send(JSON.stringify({ type, data: payload }));
  }

  onMessage(type: string, cb: Listener<unknown>): () => void {
    let set = this.messageListeners.get(type);
    if (!set) {
      set = new Set();
      this.messageListeners.set(type, set);
    }
    set.add(cb);
    return () => {
      set!.delete(cb);
    };
  }

  onStateChange(cb: Listener<ChannelState>): () => void {
    this.stateListeners.add(cb);
    return () => {
      this.stateListeners.delete(cb);
    };
  }

  onOpen(cb: Listener<void>): () => void {
    this.openListeners.add(cb);
    return () => {
      this.openListeners.delete(cb);
    };
  }

  onClose(cb: Listener<ChannelCloseEvent>): () => void {
    this.closeListeners.add(cb);
    return () => {
      this.closeListeners.delete(cb);
    };
  }

  onError(cb: Listener<unknown>): () => void {
    this.errorListeners.add(cb);
    return () => {
      this.errorListeners.delete(cb);
    };
  }

  async close(): Promise<void> {
    this.explicitClose = true;
    const sock = this.socket;
    if (!sock) return;
    if (sock.readyState === 3) return;
    await new Promise<void>((resolve) => {
      sock.addEventListener('close', () => resolve(), { once: true });
      try {
        sock.close();
      } catch {
        resolve();
      }
    });
  }

  private setState(next: ChannelState): void {
    if (this._state === next) return;
    this._state = next;
    for (const cb of this.stateListeners) cb(next);
  }

  private connect(): void {
    const url = buildUrl(this.options);
    const Impl =
      this.options.WebSocketImpl ??
      (typeof WebSocket !== 'undefined' ? WebSocket : undefined);
    if (!Impl) {
      throw new Error(
        'No WebSocket implementation available. Pass options.WebSocketImpl.',
      );
    }

    this.setState(this.attempts === 0 ? 'connecting' : 'reconnecting');

    const subprotocols: string[] = [];
    if (this.options.auth === 'subprotocol' && this.options.token !== undefined) {
      subprotocols.push('bearer', this.options.token);
    }

    const sock =
      subprotocols.length > 0
        ? new Impl(url, subprotocols)
        : new Impl(url);
    this.socket = sock;

    sock.addEventListener('open', () => {
      this.attempts = 0;
      if (this.options.auth === 'first-message') {
        const type = this.options.firstMessageType ?? '__auth';
        const payload =
          this.options.firstMessagePayload !== undefined
            ? this.options.firstMessagePayload
            : { token: this.options.token };
        try {
          sock.send(JSON.stringify({ type, data: payload }));
        } catch (err) {
          for (const cb of this.errorListeners) cb(err);
        }
      }
      this.setState('open');
      for (const cb of this.openListeners) cb();
    });

    sock.addEventListener('message', (event: MessageEvent) => {
      let envelope: ChannelEnvelope;
      try {
        const text =
          typeof event.data === 'string'
            ? event.data
            : event.data instanceof ArrayBuffer
              ? new TextDecoder().decode(event.data)
              : String(event.data);
        envelope = JSON.parse(text) as ChannelEnvelope;
      } catch (err) {
        for (const cb of this.errorListeners) cb(err);
        return;
      }
      if (typeof envelope !== 'object' || envelope === null) return;
      const set = this.messageListeners.get(envelope.type);
      if (!set) return;
      for (const cb of set) cb(envelope.data);
    });

    sock.addEventListener('error', (event: Event) => {
      for (const cb of this.errorListeners) cb(event);
    });

    sock.addEventListener('close', (event: CloseEvent) => {
      const closeInfo: ChannelCloseEvent = {
        code: event.code,
        reason: event.reason,
      };
      for (const cb of this.closeListeners) cb(closeInfo);
      if (this.explicitClose) {
        this.setState('closed');
        return;
      }
      const rc = this.options.reconnect;
      if (!rc || rc.enabled === false) {
        this.setState('closed');
        return;
      }
      const maxAttempts = rc.maxAttempts ?? 5;
      if (this.attempts >= maxAttempts) {
        this.setState('closed');
        return;
      }
      this.attempts += 1;
      const initial = rc.initialDelayMs ?? 500;
      const factor = rc.factor ?? 2;
      const max = rc.maxDelayMs ?? 10_000;
      const base = Math.min(max, initial * Math.pow(factor, this.attempts - 1));
      const delay = jitterDelay(base, rc.jitter ?? true);
      this.setState('reconnecting');
      setTimeout(() => {
        if (this.explicitClose) return;
        this.connect();
      }, delay);
    });
  }
}
`;
}
