/**
 * Top-level channel client generator.
 *
 * Walks every channel on a Triad `Router` and emits:
 *
 *   - `client.ts`   — the shared runtime wrapper
 *   - `types.ts`    — every named interface referenced by any channel
 *   - `<name>.ts`   — one typed factory per channel
 *   - `index.ts`    — a barrel re-exporting all of the above
 *
 * The generator never writes to disk — use `writeFiles` from
 * `./write.js` or the CLI integration for that.
 */

import type { Router } from '@triad/core';
import { TypeEmitter } from '@triad/tanstack-query';
import type { GenerateChannelClientOptions, GeneratedFile } from './types.js';
import { emitChannelClient } from './channel-generator.js';
import { renderClientRuntime } from './client-template.js';

const HEADER = `// Generated by @triad/channel-client — do not edit.
// Regenerate with: triad frontend generate --target channel-client\n`;

export function generateChannelClient(
  router: Router,
  options: GenerateChannelClientOptions,
): GeneratedFile[] {
  const channels = router.allChannels();
  if (channels.length === 0) return [];

  const emitter = new TypeEmitter();
  const emitRuntime = options.emitRuntime ?? true;
  const baseUrl = options.baseUrl ?? '/';

  const channelFiles = channels.map((channel) =>
    emitChannelClient(channel, emitter),
  );

  // types.ts
  const typeLines: string[] = [HEADER];
  for (const nt of emitter.namedTypes()) {
    typeLines.push(nt.source);
    typeLines.push('');
  }
  if (emitter.namedTypes().length === 0) {
    typeLines.push('export {};');
  }

  // index.ts barrel
  const indexLines: string[] = [HEADER];
  indexLines.push("export * from './types.js';");
  indexLines.push("export * from './client.js';");
  for (const cf of channelFiles) {
    const base = cf.path.replace(/\.ts$/, '');
    indexLines.push(`export * from './${base}.js';`);
  }

  const files: GeneratedFile[] = [
    { path: 'types.ts', contents: `${typeLines.join('\n')}\n` },
    ...channelFiles.map(
      (cf): GeneratedFile => ({ path: cf.path, contents: cf.contents }),
    ),
    { path: 'index.ts', contents: `${indexLines.join('\n')}\n` },
  ];

  if (emitRuntime) {
    files.push({
      path: 'client.ts',
      contents: renderClientRuntime({ baseUrl }),
    });
  }

  return files;
}
