/**
 * Top-level channel client generator.
 *
 * Walks every channel on a Triad `Router` and emits:
 *
 *   - `client.ts`   — the shared runtime wrapper
 *   - `types.ts`    — every named interface referenced by any channel
 *   - `<name>.ts`   — one typed factory per channel
 *   - `index.ts`    — a barrel re-exporting all of the above
 *
 * Optional framework targets (`channel-client-react`,
 * `channel-client-solid`, `channel-client-vue`, `channel-client-svelte`)
 * each add their own runtime file plus one per-channel hook file;
 * the vanilla client files are emitted once regardless of how many
 * framework targets are combined.
 *
 * The generator never writes to disk — use `writeFiles` from
 * `./write.js` or the CLI integration for that.
 */

import type { Router } from '@triadjs/core';
import { TypeEmitter } from '@triadjs/tanstack-query';
import type {
  ChannelClientTarget,
  GenerateChannelClientOptions,
  GeneratedFile,
} from './types.js';
import { emitChannelClient } from './channel-generator.js';
import { renderClientRuntime } from './client-template.js';
import { emitChannelReactHook } from './react-hook-generator.js';
import { renderReactRuntime } from './react-template.js';
import { emitChannelSolidHook } from './solid-hook-generator.js';
import { renderSolidRuntime } from './solid-template.js';
import { emitChannelVueHook } from './vue-hook-generator.js';
import { renderVueRuntime } from './vue-template.js';
import { emitChannelSvelteHook } from './svelte-hook-generator.js';
import { renderSvelteRuntime } from './svelte-template.js';

function normalizeTargets(
  raw: GenerateChannelClientOptions['target'],
): ReadonlySet<ChannelClientTarget> {
  if (raw === undefined) return new Set(['channel-client']);
  const values = Array.isArray(raw) ? raw : [raw];
  return new Set(values);
}

const HEADER = `// Generated by @triadjs/channel-client — do not edit.
// Regenerate with: triad frontend generate --target channel-client\n`;

export function generateChannelClient(
  router: Router,
  options: GenerateChannelClientOptions,
): GeneratedFile[] {
  const channels = router.allChannels();
  if (channels.length === 0) return [];

  const emitter = new TypeEmitter();
  const emitRuntime = options.emitRuntime ?? true;
  const baseUrl = options.baseUrl ?? '/';
  const targets = normalizeTargets(options.target);
  const includeReact = targets.has('channel-client-react');
  const includeSolid = targets.has('channel-client-solid');
  const includeVue = targets.has('channel-client-vue');
  const includeSvelte = targets.has('channel-client-svelte');

  const channelFiles = channels.map((channel) =>
    emitChannelClient(channel, emitter),
  );
  // Framework hook files walk channels against the same emitter so
  // any referenced types land in types.ts even when only a framework
  // target is used.
  const reactFiles = includeReact
    ? channels.map((channel) => emitChannelReactHook(channel, emitter))
    : [];
  const solidFiles = includeSolid
    ? channels.map((channel) => emitChannelSolidHook(channel, emitter))
    : [];
  const vueFiles = includeVue
    ? channels.map((channel) => emitChannelVueHook(channel, emitter))
    : [];
  const svelteFiles = includeSvelte
    ? channels.map((channel) => emitChannelSvelteHook(channel, emitter))
    : [];

  // types.ts
  const typeLines: string[] = [HEADER];
  for (const nt of emitter.namedTypes()) {
    typeLines.push(nt.source);
    typeLines.push('');
  }
  if (emitter.namedTypes().length === 0) {
    typeLines.push('export {};');
  }

  // index.ts barrel
  const indexLines: string[] = [HEADER];
  indexLines.push("export * from './types.js';");
  indexLines.push("export * from './client.js';");
  for (const cf of channelFiles) {
    const base = cf.path.replace(/\.ts$/, '');
    indexLines.push(`export * from './${base}.js';`);
  }
  if (includeReact) {
    indexLines.push("export * from './react-runtime.js';");
    for (const rf of reactFiles) {
      const base = rf.path.replace(/\.ts$/, '');
      indexLines.push(`export * from './${base}.js';`);
    }
  }
  if (includeSolid) {
    indexLines.push("export * from './solid-runtime.js';");
    for (const sf of solidFiles) {
      const base = sf.path.replace(/\.ts$/, '');
      indexLines.push(`export * from './${base}.js';`);
    }
  }
  if (includeVue) {
    indexLines.push("export * from './vue-runtime.js';");
    for (const vf of vueFiles) {
      const base = vf.path.replace(/\.ts$/, '');
      indexLines.push(`export * from './${base}.js';`);
    }
  }
  if (includeSvelte) {
    indexLines.push("export * from './svelte-runtime.js';");
    for (const sf of svelteFiles) {
      const base = sf.path.replace(/\.ts$/, '');
      indexLines.push(`export * from './${base}.js';`);
    }
  }

  const files: GeneratedFile[] = [
    { path: 'types.ts', contents: `${typeLines.join('\n')}\n` },
    ...channelFiles.map(
      (cf): GeneratedFile => ({ path: cf.path, contents: cf.contents }),
    ),
  ];

  if (includeReact) {
    files.push({
      path: 'react-runtime.ts',
      contents: renderReactRuntime(),
    });
    for (const rf of reactFiles) {
      files.push({ path: rf.path, contents: rf.contents });
    }
  }
  if (includeSolid) {
    files.push({
      path: 'solid-runtime.ts',
      contents: renderSolidRuntime(),
    });
    for (const sf of solidFiles) {
      files.push({ path: sf.path, contents: sf.contents });
    }
  }
  if (includeVue) {
    files.push({
      path: 'vue-runtime.ts',
      contents: renderVueRuntime(),
    });
    for (const vf of vueFiles) {
      files.push({ path: vf.path, contents: vf.contents });
    }
  }
  if (includeSvelte) {
    files.push({
      path: 'svelte-runtime.ts',
      contents: renderSvelteRuntime(),
    });
    for (const sf of svelteFiles) {
      files.push({ path: sf.path, contents: sf.contents });
    }
  }

  files.push({ path: 'index.ts', contents: `${indexLines.join('\n')}\n` });

  if (emitRuntime) {
    files.push({
      path: 'client.ts',
      contents: renderClientRuntime({ baseUrl }),
    });
  }

  return files;
}
