/**
 * Per-channel React hook emitter.
 *
 * Given a single Triad `Channel` and a shared `TypeEmitter`, produce
 * the TypeScript source for a `<name>-react.ts` file that wraps the
 * vanilla channel client (generated by `channel-generator.ts`) with a
 * typed React hook built on top of the runtime exported by
 * `react-template.ts`.
 *
 * The generated hook is called `use<PascalName>Channel` and exposes:
 *
 *   - `state`/`isOpen` driven by `useSyncExternalStore`
 *   - `send` (only if the channel has client messages)
 *   - `close()` convenience
 *   - typed `onXxx` callback options for every server message
 *
 * If the channel declares a server message named `error`, `onError`
 * is routed to that message (domain wins over lifecycle), matching
 * the vanilla channel-generator's collision resolution.
 */

import type { Channel, SchemaNode } from '@triad/core';
import { TypeEmitter } from '@triad/tanstack-query';

export interface EmittedReactHook {
  /** File path (relative to outputDir), e.g. `book-reviews-react.ts`. */
  path: string;
  /** Source contents. */
  contents: string;
  /** PascalCase base name (e.g. `BookReviews`). */
  baseName: string;
  /** Hook function name, e.g. `useBookReviewsChannel`. */
  hookName: string;
  /** Named type references the file imports from `./types.js`. */
  typeImports: string[];
}

function toPascalCase(name: string): string {
  return name
    .replace(/[_-]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function toKebabCase(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}

function messageToHandlerName(messageType: string): string {
  return `on${toPascalCase(messageType)}`;
}

const TYPE_REF_RE = /\b([A-Z][A-Za-z0-9_]*)\b/g;
const BUILTIN = new Set([
  'Array',
  'Record',
  'Partial',
  'Readonly',
  'ReadonlyArray',
  'Promise',
  'Map',
  'Set',
  'Date',
  'Buffer',
  'Uint8Array',
  'ArrayBuffer',
]);

function collectTypeRefs(type: string, out: Set<string>): void {
  let match: RegExpExecArray | null;
  TYPE_REF_RE.lastIndex = 0;
  while ((match = TYPE_REF_RE.exec(type)) !== null) {
    const ref = match[1]!;
    if (!BUILTIN.has(ref)) out.add(ref);
  }
}

interface ShapeField {
  name: string;
  type: string;
}

function walkInlineShape(
  emitter: TypeEmitter,
  model:
    | {
        readonly shape?: Record<string, SchemaNode>;
      }
    | undefined,
  typeImports: Set<string>,
): ShapeField[] {
  if (!model || !model.shape) return [];
  const fields: ShapeField[] = [];
  for (const [fieldName, fieldSchema] of Object.entries(model.shape)) {
    const typeStr = emitter.emitType(fieldSchema);
    collectTypeRefs(typeStr, typeImports);
    fields.push({ name: fieldName, type: typeStr });
  }
  return fields;
}

export function emitChannelReactHook(
  channel: Channel,
  emitter: TypeEmitter,
): EmittedReactHook {
  const baseName = toPascalCase(channel.name);
  const hookName = `use${baseName}Channel`;
  const kebab = toKebabCase(channel.name);
  const typeImports = new Set<string>();

  // Walk the connection shapes and message schemas through the shared
  // `TypeEmitter` so the generator main pass registers every named
  // model in `types.ts` even when only the React target is used.
  walkInlineShape(emitter, channel.connection.params, typeImports);
  walkInlineShape(emitter, channel.connection.query, typeImports);
  walkInlineShape(emitter, channel.connection.headers, typeImports);

  interface MsgRef {
    type: string;
    tsType: string;
  }
  const clientMessages: MsgRef[] = [];
  for (const [type, config] of Object.entries(channel.clientMessages)) {
    const tsType = emitter.emitType(config.schema);
    collectTypeRefs(tsType, typeImports);
    clientMessages.push({ type, tsType });
  }
  const serverMessages: MsgRef[] = [];
  for (const [type, config] of Object.entries(channel.serverMessages)) {
    const tsType = emitter.emitType(config.schema);
    collectTypeRefs(tsType, typeImports);
    serverMessages.push({ type, tsType });
  }

  const hasClientMessages = clientMessages.length > 0;
  const hasServerMessages = serverMessages.length > 0;
  const hasErrorMessage = serverMessages.some((m) => m.type === 'error');

  // ---- Emit --------------------------------------------------------------
  const lines: string[] = [];
  lines.push('// Generated by @triad/channel-client — do not edit.');
  lines.push(
    '// Regenerate with: triad frontend generate --target channel-client-react',
  );
  lines.push('');
  lines.push("import { useEffect } from 'react';");
  lines.push(
    "import { useTriadChannelLifecycle } from './react-runtime.js';",
  );
  const factoryImports = [
    `create${baseName}Client`,
    `type ${baseName}Client`,
    `type ${baseName}ClientOptions`,
  ];
  lines.push(
    `import { ${factoryImports.join(', ')} } from './${kebab}.js';`,
  );
  lines.push("import type { ChannelState } from './client.js';");
  if (typeImports.size > 0) {
    const sorted = Array.from(typeImports).sort();
    lines.push(`import type { ${sorted.join(', ')} } from './types.js';`);
  }
  lines.push('');

  // ---- Options interface -------------------------------------------------
  if (hasErrorMessage) {
    lines.push('/**');
    lines.push(
      " * This channel declares an `error` server message, so `onError` delivers the channel's `error` server message",
    );
    lines.push(
      ' * (the domain error), not a lifecycle error event. Use the vanilla client directly if you',
    );
    lines.push(' * need to observe socket-level errors.');
    lines.push(' */');
  }
  lines.push(
    `export interface Use${baseName}ChannelOptions extends ${baseName}ClientOptions {`,
  );
  lines.push('  /** When `false`, the hook does not open the channel. Default: `true`. */');
  lines.push('  enabled?: boolean;');
  for (const m of serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push(
      `  ${handler}?: (payload: ${m.tsType}) => void;`,
    );
  }
  lines.push('}');
  lines.push('');

  // ---- Result interface --------------------------------------------------
  lines.push(`export interface Use${baseName}ChannelResult {`);
  lines.push('  /** Current channel state. Re-renders on transition. */');
  lines.push('  state: ChannelState;');
  lines.push("  /** Convenience flag: `state === 'open'`. */");
  lines.push('  isOpen: boolean;');
  if (hasClientMessages) {
    lines.push(`  /** Typed outbound message surface. */`);
    lines.push(`  send: ${baseName}Client['send'];`);
  }
  lines.push('  /** Close the channel. Called automatically on unmount. */');
  lines.push('  close: () => Promise<void>;');
  lines.push('}');
  lines.push('');

  // ---- Hook function -----------------------------------------------------
  lines.push(
    `export function ${hookName}(options: Use${baseName}ChannelOptions): Use${baseName}ChannelResult {`,
  );
  // Destructure enabled + handlers out of options, leaving clientOptions
  // for the factory.
  const destructured = ['enabled = true'];
  for (const m of serverMessages) {
    destructured.push(messageToHandlerName(m.type));
  }
  destructured.push('...clientOptions');
  lines.push(`  const { ${destructured.join(', ')} } = options;`);
  lines.push('');
  lines.push('  const { client, state, isOpen } = useTriadChannelLifecycle(');
  lines.push('    () => createBookReviewsClient_placeholder(clientOptions),'.replace('createBookReviewsClient_placeholder', `create${baseName}Client`));
  lines.push('    { enabled },');
  lines.push('  );');
  lines.push('');

  // Per-handler useEffect blocks.
  for (const m of serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push('  useEffect(() => {');
    lines.push(`    if (!${handler}) return;`);
    lines.push(`    return client.on('${m.type}', ${handler});`);
    lines.push(`  }, [client, ${handler}]);`);
    lines.push('');
  }

  lines.push('  return {');
  lines.push('    state,');
  lines.push('    isOpen,');
  if (hasClientMessages) {
    lines.push('    send: client.send,');
  }
  lines.push('    close: () => client.close(),');
  lines.push('  };');
  lines.push('}');
  lines.push('');

  // Suppress unused-import warning for hasServerMessages=false case.
  void hasServerMessages;

  return {
    path: `${kebab}-react.ts`,
    contents: lines.join('\n'),
    baseName,
    hookName,
    typeImports: Array.from(typeImports),
  };
}
