/**
 * Per-channel React hook emitter.
 *
 * Given a single Triad `Channel` and a shared `TypeEmitter`, produce
 * the TypeScript source for a `<name>-react.ts` file that wraps the
 * vanilla channel client (generated by `channel-generator.ts`) with a
 * typed React hook built on top of the runtime exported by
 * `react-template.ts`.
 *
 * The generated hook is called `use<PascalName>Channel` and exposes:
 *
 *   - `state`/`isOpen` driven by `useSyncExternalStore`
 *   - `send` (only if the channel has client messages)
 *   - `close()` convenience
 *   - typed `onXxx` callback options for every server message
 *
 * If the channel declares a server message named `error`, `onError`
 * is routed to that message (domain wins over lifecycle), matching
 * the vanilla channel-generator's collision resolution.
 */

import type { Channel } from '@triadjs/core';
import type { TypeEmitter } from '@triadjs/tanstack-query';
import {
  analyzeChannel,
  messageToHandlerName,
  type ChannelHookAnalysis,
} from './hook-analysis.js';

export interface EmittedReactHook {
  /** File path (relative to outputDir), e.g. `book-reviews-react.ts`. */
  path: string;
  /** Source contents. */
  contents: string;
  /** PascalCase base name (e.g. `BookReviews`). */
  baseName: string;
  /** Hook function name, e.g. `useBookReviewsChannel`. */
  hookName: string;
  /** Named type references the file imports from `./types.js`. */
  typeImports: string[];
}

export function emitChannelReactHook(
  channel: Channel,
  emitter: TypeEmitter,
): EmittedReactHook {
  const a: ChannelHookAnalysis = analyzeChannel(channel, emitter);
  const hookName = `use${a.pascal}Channel`;

  // ---- Emit --------------------------------------------------------------
  const lines: string[] = [];
  lines.push('// Generated by @triadjs/channel-client — do not edit.');
  lines.push(
    '// Regenerate with: triad frontend generate --target channel-client-react',
  );
  lines.push('');
  lines.push("import { useEffect } from 'react';");
  lines.push(
    "import { useTriadChannelLifecycle } from './react-runtime.js';",
  );
  const factoryImports = [
    `create${a.pascal}Client`,
    `type ${a.pascal}Client`,
    `type ${a.pascal}ClientOptions`,
  ];
  lines.push(
    `import { ${factoryImports.join(', ')} } from './${a.kebab}.js';`,
  );
  lines.push("import type { ChannelState } from './client.js';");
  if (a.typeImports.length > 0) {
    lines.push(`import type { ${a.typeImports.join(', ')} } from './types.js';`);
  }
  lines.push('');

  // ---- Options interface -------------------------------------------------
  if (a.hasErrorMessage) {
    lines.push('/**');
    lines.push(
      " * This channel declares an `error` server message, so `onError` delivers the channel's `error` server message",
    );
    lines.push(
      ' * (the domain error), not a lifecycle error event. Use the vanilla client directly if you',
    );
    lines.push(' * need to observe socket-level errors.');
    lines.push(' */');
  }
  lines.push(
    `export interface Use${a.pascal}ChannelOptions extends ${a.pascal}ClientOptions {`,
  );
  lines.push('  /** When `false`, the hook does not open the channel. Default: `true`. */');
  lines.push('  enabled?: boolean;');
  for (const m of a.serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push(
      `  ${handler}?: (payload: ${m.tsType}) => void;`,
    );
  }
  lines.push('}');
  lines.push('');

  // ---- Result interface --------------------------------------------------
  lines.push(`export interface Use${a.pascal}ChannelResult {`);
  lines.push('  /** Current channel state. Re-renders on transition. */');
  lines.push('  state: ChannelState;');
  lines.push("  /** Convenience flag: `state === 'open'`. */");
  lines.push('  isOpen: boolean;');
  if (a.hasClientMessages) {
    lines.push(`  /** Typed outbound message surface. */`);
    lines.push(`  send: ${a.pascal}Client['send'];`);
  }
  lines.push('  /** Close the channel. Called automatically on unmount. */');
  lines.push('  close: () => Promise<void>;');
  lines.push('}');
  lines.push('');

  // ---- Hook function -----------------------------------------------------
  lines.push(
    `export function ${hookName}(options: Use${a.pascal}ChannelOptions): Use${a.pascal}ChannelResult {`,
  );
  const destructured = ['enabled = true'];
  for (const m of a.serverMessages) {
    destructured.push(messageToHandlerName(m.type));
  }
  destructured.push('...clientOptions');
  lines.push(`  const { ${destructured.join(', ')} } = options;`);
  lines.push('');
  lines.push('  const { client, state, isOpen } = useTriadChannelLifecycle(');
  lines.push(`    () => create${a.pascal}Client(clientOptions),`);
  lines.push('    { enabled },');
  lines.push('  );');
  lines.push('');

  // Per-handler useEffect blocks.
  for (const m of a.serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push('  useEffect(() => {');
    lines.push(`    if (!${handler}) return;`);
    lines.push(`    return client.on('${m.type}', ${handler});`);
    lines.push(`  }, [client, ${handler}]);`);
    lines.push('');
  }

  lines.push('  return {');
  lines.push('    state,');
  lines.push('    isOpen,');
  if (a.hasClientMessages) {
    lines.push('    send: client.send,');
  }
  lines.push('    close: () => client.close(),');
  lines.push('  };');
  lines.push('}');
  lines.push('');

  // Suppress unused-import warning for hasServerMessages=false case.
  void a.hasServerMessages;

  return {
    path: `${a.kebab}-react.ts`,
    contents: lines.join('\n'),
    baseName: a.pascal,
    hookName,
    typeImports: [...a.typeImports],
  };
}
