/**
 * Per-channel Solid hook emitter.
 *
 * Given a single Triad `Channel` and a shared `TypeEmitter`, produce
 * the TypeScript source for a `<name>-solid.ts` file that wraps the
 * vanilla channel client (from `channel-generator.ts`) with a typed
 * Solid reactive factory built on the runtime exported by
 * `solid-template.ts`.
 *
 * The generated factory is called `create<PascalName>Channel` —
 * mirroring Solid Query's `createQuery`/`createMutation` naming —
 * and exposes:
 *
 *   - `state`/`isOpen` as `Accessor<T>` signals
 *   - `send` (only if the channel has client messages)
 *   - `close()` convenience
 *   - typed `onXxx` callback options for every server message
 *
 * If the channel declares a server message named `error`, `onError`
 * is routed to that message (domain wins over lifecycle), matching
 * the vanilla channel-generator's collision resolution.
 */

import type { Channel } from '@triadjs/core';
import type { TypeEmitter } from '@triadjs/tanstack-query';
import {
  analyzeChannel,
  messageToHandlerName,
  type ChannelHookAnalysis,
} from './hook-analysis.js';

export interface EmittedSolidHook {
  /** File path (relative to outputDir), e.g. `book-reviews-solid.ts`. */
  path: string;
  /** Source contents. */
  contents: string;
  /** PascalCase base name (e.g. `BookReviews`). */
  baseName: string;
  /** Factory function name, e.g. `createBookReviewsChannel`. */
  hookName: string;
  /** Named type references the file imports from `./types.js`. */
  typeImports: string[];
}

export function emitChannelSolidHook(
  channel: Channel,
  emitter: TypeEmitter,
): EmittedSolidHook {
  const a: ChannelHookAnalysis = analyzeChannel(channel, emitter);
  const hookName = `create${a.pascal}Channel`;

  const lines: string[] = [];
  lines.push('// Generated by @triadjs/channel-client — do not edit.');
  lines.push(
    '// Regenerate with: triad frontend generate --target channel-client-solid',
  );
  lines.push('');
  lines.push(
    "import { createEffect, onCleanup, type Accessor } from 'solid-js';",
  );
  lines.push(
    "import { createTriadChannelLifecycle } from './solid-runtime.js';",
  );
  const factoryImports = [
    `create${a.pascal}Client`,
    `type ${a.pascal}Client`,
    `type ${a.pascal}ClientOptions`,
  ];
  lines.push(
    `import { ${factoryImports.join(', ')} } from './${a.kebab}.js';`,
  );
  lines.push("import type { ChannelState } from './client.js';");
  if (a.typeImports.length > 0) {
    lines.push(`import type { ${a.typeImports.join(', ')} } from './types.js';`);
  }
  lines.push('');

  if (a.hasErrorMessage) {
    lines.push('/**');
    lines.push(
      " * This channel declares an `error` server message, so `onError` delivers the channel's `error` server message",
    );
    lines.push(
      ' * (the domain error), not a lifecycle error event. Use the vanilla client directly if you',
    );
    lines.push(' * need to observe socket-level errors.');
    lines.push(' */');
  }
  lines.push(
    `export interface Use${a.pascal}ChannelOptions extends ${a.pascal}ClientOptions {`,
  );
  lines.push(
    '  /** When `false`, the factory does not open the channel. Default: `true`. */',
  );
  lines.push('  enabled?: Accessor<boolean> | boolean;');
  for (const m of a.serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push(`  ${handler}?: (payload: ${m.tsType}) => void;`);
  }
  lines.push('}');
  lines.push('');

  lines.push(`export interface Use${a.pascal}ChannelResult {`);
  lines.push('  /** Accessor for the current channel state. */');
  lines.push('  state: Accessor<ChannelState>;');
  lines.push("  /** Accessor equivalent to `state() === 'open'`. */");
  lines.push('  isOpen: Accessor<boolean>;');
  if (a.hasClientMessages) {
    lines.push('  /** Typed outbound message surface. */');
    lines.push(`  send: ${a.pascal}Client['send'];`);
  }
  lines.push(
    '  /** Close the channel. Called automatically on component cleanup. */',
  );
  lines.push('  close: () => Promise<void>;');
  lines.push('}');
  lines.push('');

  lines.push(
    `export function ${hookName}(options: Use${a.pascal}ChannelOptions): Use${a.pascal}ChannelResult {`,
  );
  const destructured = ['enabled'];
  for (const m of a.serverMessages) {
    destructured.push(messageToHandlerName(m.type));
  }
  destructured.push('...clientOptions');
  lines.push(`  const { ${destructured.join(', ')} } = options;`);
  lines.push('');
  lines.push('  const { client, state, isOpen } = createTriadChannelLifecycle(');
  lines.push(`    () => create${a.pascal}Client(clientOptions),`);
  lines.push('    { enabled },');
  lines.push('  );');
  lines.push('');

  if (a.hasClientMessages) {
    lines.push(`  const send: ${a.pascal}Client['send'] = new Proxy(`);
    lines.push(`    {} as ${a.pascal}Client['send'],`);
    lines.push('    {');
    lines.push('      get(_target, prop): unknown {');
    lines.push('        return (payload: unknown): void => {');
    lines.push('          const current = client();');
    lines.push('          if (current === null) {');
    lines.push(
      "            throw new Error('Cannot send on a disabled or closed channel.');",
    );
    lines.push('          }');
    lines.push(
      '          (current.send as unknown as Record<string, (p: unknown) => void>)[prop as string]!(payload);',
    );
    lines.push('        };');
    lines.push('      },');
    lines.push('    },');
    lines.push('  );');
    lines.push('');
  }

  for (const m of a.serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push('  createEffect(() => {');
    lines.push('    const current = client();');
    lines.push(`    if (current === null || !${handler}) return;`);
    lines.push(`    const unsubscribe = current.on('${m.type}', ${handler});`);
    lines.push('    onCleanup(() => unsubscribe());');
    lines.push('  });');
    lines.push('');
  }

  lines.push('  return {');
  lines.push('    state,');
  lines.push('    isOpen,');
  if (a.hasClientMessages) {
    lines.push('    send,');
  }
  lines.push('    close: async (): Promise<void> => {');
  lines.push('      const current = client();');
  lines.push('      if (current !== null) await current.close();');
  lines.push('    },');
  lines.push('  };');
  lines.push('}');
  lines.push('');

  void a.hasServerMessages;

  return {
    path: `${a.kebab}-solid.ts`,
    contents: lines.join('\n'),
    baseName: a.pascal,
    hookName,
    typeImports: [...a.typeImports],
  };
}
