/**
 * Solid runtime template.
 *
 * Exports `renderSolidRuntime()` returning the TypeScript source
 * emitted alongside generated Solid channel hooks. The runtime owns
 * a tiny `createTriadChannelLifecycle` primitive that wraps a
 * vanilla `BaseChannelClient`-shaped object in Solid signals and
 * attaches a cleanup on unmount.
 *
 * The runtime has no compile-time dependency on any particular
 * channel: it is parametric over `TClient extends TriadChannelClientLike`.
 * Per-channel factories (emitted by `solid-hook-generator.ts`) wrap
 * it with typed message callbacks.
 */

export function renderSolidRuntime(): string {
  return `// Generated by @triad/channel-client — do not edit.
// Regenerate with: triad frontend generate --target channel-client-solid

import { createSignal, createEffect, onCleanup, type Accessor } from 'solid-js';
import type { ChannelState } from './client.js';

/**
 * Minimal structural shape every generated channel client satisfies.
 * The Solid lifecycle primitive works against this interface so it
 * does not need a per-channel import.
 */
export interface TriadChannelClientLike {
  readonly state: ChannelState;
  on(event: 'stateChange', cb: (state: ChannelState) => void): () => void;
  close(): Promise<void>;
}

export interface CreateTriadChannelResult<TClient extends TriadChannelClientLike> {
  /** Accessor returning the live client, or \`null\` while disabled. */
  client: Accessor<TClient | null>;
  /** Current connection state. Updates reactively on transition. */
  state: Accessor<ChannelState>;
  /** Convenience accessor equivalent to \`state() === 'open'\`. */
  isOpen: Accessor<boolean>;
}

export interface CreateTriadChannelLifecycleOptions {
  /**
   * When \`false\` (or returns \`false\`), no client is created and
   * the result reports \`'closed'\`. Flipping back to \`true\` creates
   * a fresh client. Defaults to \`true\`.
   */
  enabled?: Accessor<boolean> | boolean;
}

function resolveEnabled(value: Accessor<boolean> | boolean | undefined): boolean {
  if (value === undefined) return true;
  if (typeof value === 'boolean') return value;
  return value();
}

/**
 * Own a channel client across the lifetime of a Solid component.
 *
 * - The factory is invoked once per enabled reactivation.
 * - When \`enabled\` flips false, or the component unmounts, the
 *   previous client's \`close()\` is called.
 * - State updates flow through a signal, so Solid's reactivity picks
 *   up \`connecting → open\` transitions automatically.
 *
 * Changing connection options (url, params, headers) at runtime is
 * NOT supported: the factory runs once per enabled edge. To reconnect
 * against different options, re-mount the component.
 */
export function createTriadChannelLifecycle<TClient extends TriadChannelClientLike>(
  factory: () => TClient,
  options?: CreateTriadChannelLifecycleOptions,
): CreateTriadChannelResult<TClient> {
  const [client, setClient] = createSignal<TClient | null>(null);
  const [state, setState] = createSignal<ChannelState>('closed');

  createEffect(() => {
    const enabled = resolveEnabled(options?.enabled);
    if (!enabled) {
      const existing = client();
      setClient(null);
      setState('closed');
      if (existing !== null) void existing.close();
      return;
    }
    const instance = factory();
    setClient(() => instance);
    setState(instance.state);
    const unsubscribe = instance.on('stateChange', (next) => setState(next));
    onCleanup(() => {
      unsubscribe();
      setClient(null);
      setState('closed');
      void instance.close();
    });
  });

  const isOpen: Accessor<boolean> = () => state() === 'open';
  return { client, state, isOpen };
}
`;
}
