/**
 * Svelte runtime template.
 *
 * Exports `renderSvelteRuntime()` returning the TypeScript source
 * emitted alongside generated Svelte channel hooks. The runtime
 * exposes `triadChannelLifecycle`, a generic factory that wraps a
 * vanilla `BaseChannelClient`-shaped object in a `Readable<ChannelState>`
 * store and registers an `onDestroy` cleanup.
 *
 * The runtime is parametric over `TClient extends TriadChannelClientLike`.
 * Per-channel factories (emitted by `svelte-hook-generator.ts`) wrap
 * it with typed message callbacks.
 */

export function renderSvelteRuntime(): string {
  return `// Generated by @triad/channel-client — do not edit.
// Regenerate with: triad frontend generate --target channel-client-svelte

import { writable, derived, type Readable } from 'svelte/store';
import { onDestroy } from 'svelte';
import type { ChannelState } from './client.js';

/**
 * Minimal structural shape every generated channel client satisfies.
 * The Svelte lifecycle factory works against this interface so it
 * does not need a per-channel import.
 */
export interface TriadChannelClientLike {
  readonly state: ChannelState;
  on(event: 'stateChange', cb: (state: ChannelState) => void): () => void;
  close(): Promise<void>;
}

export interface TriadChannelLifecycleResult<TClient extends TriadChannelClientLike> {
  /** The live client. Stable for the lifetime of the component. */
  client: TClient;
  /** Readable store tracking the channel's current state. */
  state: Readable<ChannelState>;
  /** Derived readable store equivalent to \`$state === 'open'\`. */
  isOpen: Readable<boolean>;
}

/**
 * Own a channel client across the lifetime of a Svelte component.
 *
 * - The factory is invoked exactly once.
 * - On component destruction (\`onDestroy\`), \`client.close()\` is
 *   called and the state store is forced to \`'closed'\`.
 * - State updates flow through a writable store the runtime owns;
 *   the public store is a \`Readable\` projection so consumers
 *   cannot mutate it.
 *
 * Changing connection options (url, params, headers) at runtime is
 * NOT supported: the factory runs once per component mount. To
 * reconnect against different options, re-mount the component.
 */
export function triadChannelLifecycle<TClient extends TriadChannelClientLike>(
  factory: () => TClient,
): TriadChannelLifecycleResult<TClient> {
  const client = factory();
  const stateStore = writable<ChannelState>(client.state);
  const unsubscribe = client.on('stateChange', (next) => {
    stateStore.set(next);
  });

  onDestroy(() => {
    unsubscribe();
    stateStore.set('closed');
    void client.close();
  });

  const isOpen: Readable<boolean> = derived(stateStore, (s) => s === 'open');
  return { client, state: stateStore, isOpen };
}
`;
}
