/**
 * Per-channel Svelte hook emitter.
 *
 * Given a single Triad `Channel` and a shared `TypeEmitter`, produce
 * the TypeScript source for a `<name>-svelte.ts` file that wraps the
 * vanilla channel client with a typed Svelte store-based factory
 * built on the runtime exported by `svelte-template.ts`.
 *
 * The generated factory is called `<camelName>Channel` (lowercase-
 * first; Svelte store-creator convention has no `use`/`create`
 * prefix) and exposes:
 *
 *   - `state` as a `Readable<ChannelState>` store
 *   - `isOpen` as a derived `Readable<boolean>` store
 *   - `send` (only if the channel has client messages)
 *   - `close()` convenience
 *   - typed `onXxx` callback options for every server message
 *
 * If the channel declares a server message named `error`, `onError`
 * is routed to that message (domain wins over lifecycle), matching
 * the vanilla channel-generator's collision resolution.
 */

import type { Channel } from '@triadjs/core';
import type { TypeEmitter } from '@triadjs/tanstack-query';
import {
  analyzeChannel,
  messageToHandlerName,
  type ChannelHookAnalysis,
} from './hook-analysis.js';

export interface EmittedSvelteHook {
  path: string;
  contents: string;
  baseName: string;
  hookName: string;
  typeImports: string[];
}

export function emitChannelSvelteHook(
  channel: Channel,
  emitter: TypeEmitter,
): EmittedSvelteHook {
  const a: ChannelHookAnalysis = analyzeChannel(channel, emitter);
  const hookName = `${a.camel}Channel`;

  const lines: string[] = [];
  lines.push('// Generated by @triadjs/channel-client — do not edit.');
  lines.push(
    '// Regenerate with: triad frontend generate --target channel-client-svelte',
  );
  lines.push('');
  lines.push("import { onDestroy } from 'svelte';");
  lines.push("import type { Readable } from 'svelte/store';");
  lines.push(
    "import { triadChannelLifecycle } from './svelte-runtime.js';",
  );
  const factoryImports = [
    `create${a.pascal}Client`,
    `type ${a.pascal}Client`,
    `type ${a.pascal}ClientOptions`,
  ];
  lines.push(
    `import { ${factoryImports.join(', ')} } from './${a.kebab}.js';`,
  );
  lines.push("import type { ChannelState } from './client.js';");
  if (a.typeImports.length > 0) {
    lines.push(`import type { ${a.typeImports.join(', ')} } from './types.js';`);
  }
  lines.push('');

  if (a.hasErrorMessage) {
    lines.push('/**');
    lines.push(
      " * This channel declares an `error` server message, so `onError` delivers the channel's `error` server message",
    );
    lines.push(
      ' * (the domain error), not a lifecycle error event. Use the vanilla client directly if you',
    );
    lines.push(' * need to observe socket-level errors.');
    lines.push(' */');
  }
  lines.push(
    `export interface Use${a.pascal}ChannelOptions extends ${a.pascal}ClientOptions {`,
  );
  lines.push(
    '  /** When `false`, the factory does not open the channel. Default: `true`. */',
  );
  lines.push('  enabled?: boolean;');
  for (const m of a.serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push(`  ${handler}?: (payload: ${m.tsType}) => void;`);
  }
  lines.push('}');
  lines.push('');

  lines.push(`export interface Use${a.pascal}ChannelResult {`);
  lines.push('  /** Readable store tracking channel state. */');
  lines.push('  state: Readable<ChannelState>;');
  lines.push("  /** Derived store equivalent to `$state === 'open'`. */");
  lines.push('  isOpen: Readable<boolean>;');
  if (a.hasClientMessages) {
    lines.push('  /** Typed outbound message surface. */');
    lines.push(`  send: ${a.pascal}Client['send'];`);
  }
  lines.push(
    '  /** Close the channel. Called automatically on component destroy. */',
  );
  lines.push('  close: () => Promise<void>;');
  lines.push('}');
  lines.push('');

  lines.push(
    `export function ${hookName}(options: Use${a.pascal}ChannelOptions): Use${a.pascal}ChannelResult {`,
  );
  const destructured = ['enabled = true'];
  for (const m of a.serverMessages) {
    destructured.push(messageToHandlerName(m.type));
  }
  destructured.push('...clientOptions');
  lines.push(`  const { ${destructured.join(', ')} } = options;`);
  lines.push('');

  lines.push('  if (!enabled) {');
  lines.push(
    "    const closedState: Readable<ChannelState> = { subscribe: (cb) => { cb('closed'); return () => {}; } };",
  );
  lines.push(
    '    const falseStore: Readable<boolean> = { subscribe: (cb) => { cb(false); return () => {}; } };',
  );
  if (a.hasClientMessages) {
    lines.push(`    const disabledSend: ${a.pascal}Client['send'] = new Proxy(`);
    lines.push(`      {} as ${a.pascal}Client['send'],`);
    lines.push('      {');
    lines.push('        get(): unknown {');
    lines.push('          return (): void => {');
    lines.push(
      "            throw new Error('Cannot send on a disabled channel.');",
    );
    lines.push('          };');
    lines.push('        },');
    lines.push('      },');
    lines.push('    );');
  }
  lines.push('    return {');
  lines.push('      state: closedState,');
  lines.push('      isOpen: falseStore,');
  if (a.hasClientMessages) {
    lines.push('      send: disabledSend,');
  }
  lines.push('      close: async (): Promise<void> => {},');
  lines.push('    };');
  lines.push('  }');
  lines.push('');

  lines.push('  const { client, state, isOpen } = triadChannelLifecycle(');
  lines.push(`    () => create${a.pascal}Client(clientOptions),`);
  lines.push('  );');
  lines.push('');

  for (const m of a.serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push(`  if (${handler}) {`);
    lines.push(`    const unsubscribe = client.on('${m.type}', ${handler});`);
    lines.push('    onDestroy(() => unsubscribe());');
    lines.push('  }');
    lines.push('');
  }

  lines.push('  return {');
  lines.push('    state,');
  lines.push('    isOpen,');
  if (a.hasClientMessages) {
    lines.push('    send: client.send,');
  }
  lines.push('    close: (): Promise<void> => client.close(),');
  lines.push('  };');
  lines.push('}');
  lines.push('');

  void a.hasServerMessages;

  return {
    path: `${a.kebab}-svelte.ts`,
    contents: lines.join('\n'),
    baseName: a.pascal,
    hookName,
    typeImports: [...a.typeImports],
  };
}
