/**
 * Vue runtime template.
 *
 * Exports `renderVueRuntime()` returning the TypeScript source
 * emitted alongside generated Vue channel hooks. The runtime
 * exposes `useTriadChannelLifecycle`, a generic Composition API
 * primitive that owns a vanilla `BaseChannelClient`-shaped object,
 * reflects its state in a `Ref<ChannelState>`, and tears down on
 * `onBeforeUnmount`.
 *
 * The runtime is parametric over `TClient extends TriadChannelClientLike`.
 * Per-channel hooks (emitted by `vue-hook-generator.ts`) wrap it
 * with typed message callbacks.
 */

export function renderVueRuntime(): string {
  return `// Generated by @triadjs/channel-client — do not edit.
// Regenerate with: triad frontend generate --target channel-client-vue

import {
  ref,
  computed,
  onBeforeUnmount,
  watch,
  type Ref,
  type ComputedRef,
} from 'vue';
import type { ChannelState } from './client.js';

/**
 * Minimal structural shape every generated channel client satisfies.
 * The Vue lifecycle hook works against this interface so it does
 * not need a per-channel import.
 */
export interface TriadChannelClientLike {
  readonly state: ChannelState;
  on(event: 'stateChange', cb: (state: ChannelState) => void): () => void;
  close(): Promise<void>;
}

export interface UseTriadChannelResult<TClient extends TriadChannelClientLike> {
  /** Live client reference, or \`null\` while disabled. */
  client: Ref<TClient | null>;
  /** Current channel state. Updates reactively. */
  state: Ref<ChannelState>;
  /** Computed flag equivalent to \`state.value === 'open'\`. */
  isOpen: ComputedRef<boolean>;
}

export interface UseTriadChannelLifecycleOptions {
  /**
   * When \`false\` (or a ref holding \`false\`), the hook does not
   * create a client. Flipping back to \`true\` creates a fresh one.
   * Defaults to \`true\`.
   */
  enabled?: Ref<boolean> | boolean;
}

function isRef<T>(value: Ref<T> | T): value is Ref<T> {
  return (
    typeof value === 'object' &&
    value !== null &&
    'value' in (value as { value?: unknown })
  );
}

/**
 * Own a channel client across the lifetime of a Vue component.
 *
 * - The factory is invoked once per enabled edge.
 * - On unmount (\`onBeforeUnmount\`), or when \`enabled\` flips false,
 *   the previous client's \`close()\` is called.
 * - State updates flow through a \`Ref\`, so templates re-render on
 *   \`connecting → open\` transitions automatically.
 *
 * Changing connection options (url, params, headers) at runtime is
 * NOT supported: the factory runs once per enabled edge. To reconnect
 * against different options, re-mount the component via a \`key\`.
 */
export function useTriadChannelLifecycle<TClient extends TriadChannelClientLike>(
  factory: () => TClient,
  options?: UseTriadChannelLifecycleOptions,
): UseTriadChannelResult<TClient> {
  const clientRef: Ref<TClient | null> = ref<TClient | null>(null) as Ref<TClient | null>;
  const stateRef: Ref<ChannelState> = ref<ChannelState>('closed') as Ref<ChannelState>;
  let unsubscribe: (() => void) | null = null;

  const teardown = (): void => {
    if (unsubscribe !== null) {
      unsubscribe();
      unsubscribe = null;
    }
    const existing = clientRef.value;
    clientRef.value = null;
    stateRef.value = 'closed';
    if (existing !== null) void existing.close();
  };

  const setup = (): void => {
    const instance = factory();
    clientRef.value = instance;
    stateRef.value = instance.state;
    unsubscribe = instance.on('stateChange', (next) => {
      stateRef.value = next;
    });
  };

  const enabledOption = options?.enabled;
  const initialEnabled =
    enabledOption === undefined
      ? true
      : typeof enabledOption === 'boolean'
        ? enabledOption
        : enabledOption.value;

  if (initialEnabled) setup();

  if (enabledOption !== undefined && isRef(enabledOption)) {
    watch(enabledOption, (next) => {
      if (next) {
        if (clientRef.value === null) setup();
        return;
      }
      teardown();
    });
  }

  onBeforeUnmount(() => {
    teardown();
  });

  const isOpen: ComputedRef<boolean> = computed(() => stateRef.value === 'open');
  return { client: clientRef, state: stateRef, isOpen };
}
`;
}
