/**
 * Per-channel Vue hook emitter.
 *
 * Given a single Triad `Channel` and a shared `TypeEmitter`, produce
 * the TypeScript source for a `<name>-vue.ts` file that wraps the
 * vanilla channel client with a typed Vue Composition API hook
 * built on the runtime exported by `vue-template.ts`.
 *
 * The generated hook is called `use<PascalName>Channel` (Vue uses
 * the `use*` prefix for composables) and exposes:
 *
 *   - `state` as a `Ref<ChannelState>`
 *   - `isOpen` as a `ComputedRef<boolean>`
 *   - `send` (only if the channel has client messages)
 *   - `close()` convenience
 *   - typed `onXxx` callback options for every server message
 *
 * If the channel declares a server message named `error`, `onError`
 * is routed to that message (domain wins over lifecycle), matching
 * the vanilla channel-generator's collision resolution.
 */

import type { Channel } from '@triad/core';
import type { TypeEmitter } from '@triad/tanstack-query';
import {
  analyzeChannel,
  messageToHandlerName,
  type ChannelHookAnalysis,
} from './hook-analysis.js';

export interface EmittedVueHook {
  path: string;
  contents: string;
  baseName: string;
  hookName: string;
  typeImports: string[];
}

export function emitChannelVueHook(
  channel: Channel,
  emitter: TypeEmitter,
): EmittedVueHook {
  const a: ChannelHookAnalysis = analyzeChannel(channel, emitter);
  const hookName = `use${a.pascal}Channel`;

  const lines: string[] = [];
  lines.push('// Generated by @triad/channel-client — do not edit.');
  lines.push(
    '// Regenerate with: triad frontend generate --target channel-client-vue',
  );
  lines.push('');
  lines.push(
    "import { watch, type ComputedRef, type Ref } from 'vue';",
  );
  lines.push(
    "import { useTriadChannelLifecycle } from './vue-runtime.js';",
  );
  const factoryImports = [
    `create${a.pascal}Client`,
    `type ${a.pascal}Client`,
    `type ${a.pascal}ClientOptions`,
  ];
  lines.push(
    `import { ${factoryImports.join(', ')} } from './${a.kebab}.js';`,
  );
  lines.push("import type { ChannelState } from './client.js';");
  if (a.typeImports.length > 0) {
    lines.push(`import type { ${a.typeImports.join(', ')} } from './types.js';`);
  }
  lines.push('');

  if (a.hasErrorMessage) {
    lines.push('/**');
    lines.push(
      " * This channel declares an `error` server message, so `onError` delivers the channel's `error` server message",
    );
    lines.push(
      ' * (the domain error), not a lifecycle error event. Use the vanilla client directly if you',
    );
    lines.push(' * need to observe socket-level errors.');
    lines.push(' */');
  }
  lines.push(
    `export interface Use${a.pascal}ChannelOptions extends ${a.pascal}ClientOptions {`,
  );
  lines.push(
    '  /** When `false`, the hook does not open the channel. Default: `true`. */',
  );
  lines.push('  enabled?: Ref<boolean> | boolean;');
  for (const m of a.serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push(`  ${handler}?: (payload: ${m.tsType}) => void;`);
  }
  lines.push('}');
  lines.push('');

  lines.push(`export interface Use${a.pascal}ChannelResult {`);
  lines.push('  /** Reactive channel state. */');
  lines.push('  state: Ref<ChannelState>;');
  lines.push("  /** Computed flag equivalent to `state.value === 'open'`. */");
  lines.push('  isOpen: ComputedRef<boolean>;');
  if (a.hasClientMessages) {
    lines.push('  /** Typed outbound message surface. */');
    lines.push(`  send: ${a.pascal}Client['send'];`);
  }
  lines.push(
    '  /** Close the channel. Called automatically on component unmount. */',
  );
  lines.push('  close: () => Promise<void>;');
  lines.push('}');
  lines.push('');

  lines.push(
    `export function ${hookName}(options: Use${a.pascal}ChannelOptions): Use${a.pascal}ChannelResult {`,
  );
  const destructured = ['enabled'];
  for (const m of a.serverMessages) {
    destructured.push(messageToHandlerName(m.type));
  }
  destructured.push('...clientOptions');
  lines.push(`  const { ${destructured.join(', ')} } = options;`);
  lines.push('');
  lines.push('  const { client, state, isOpen } = useTriadChannelLifecycle(');
  lines.push(`    () => create${a.pascal}Client(clientOptions),`);
  lines.push('    { enabled },');
  lines.push('  );');
  lines.push('');

  if (a.hasClientMessages) {
    lines.push(`  const send: ${a.pascal}Client['send'] = new Proxy(`);
    lines.push(`    {} as ${a.pascal}Client['send'],`);
    lines.push('    {');
    lines.push('      get(_target, prop): unknown {');
    lines.push('        return (payload: unknown): void => {');
    lines.push('          const current = client.value;');
    lines.push('          if (current === null) {');
    lines.push(
      "            throw new Error('Cannot send on a disabled or closed channel.');",
    );
    lines.push('          }');
    lines.push(
      '          (current.send as unknown as Record<string, (p: unknown) => void>)[prop as string]!(payload);',
    );
    lines.push('        };');
    lines.push('      },');
    lines.push('    },');
    lines.push('  );');
    lines.push('');
  }

  for (const m of a.serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push('  watch(');
    lines.push('    client,');
    lines.push('    (current, _prev, onCleanup): void => {');
    lines.push(`      if (current === null || !${handler}) return;`);
    lines.push(`      const unsubscribe = current.on('${m.type}', ${handler});`);
    lines.push('      onCleanup(() => unsubscribe());');
    lines.push('    },');
    lines.push('    { immediate: true },');
    lines.push('  );');
    lines.push('');
  }

  lines.push('  return {');
  lines.push('    state,');
  lines.push('    isOpen,');
  if (a.hasClientMessages) {
    lines.push('    send,');
  }
  lines.push('    close: async (): Promise<void> => {');
  lines.push('      const current = client.value;');
  lines.push('      if (current !== null) await current.close();');
  lines.push('    },');
  lines.push('  };');
  lines.push('}');
  lines.push('');

  void a.hasServerMessages;

  return {
    path: `${a.kebab}-vue.ts`,
    contents: lines.join('\n'),
    baseName: a.pascal,
    hookName,
    typeImports: [...a.typeImports],
  };
}
