/**
 * Per-channel Vue hook emitter.
 *
 * Given a single Triad `Channel` and a shared `TypeEmitter`, produce
 * the TypeScript source for a `<name>-vue.ts` file that wraps the
 * vanilla channel client with a typed Vue Composition API hook
 * built on the runtime exported by `vue-template.ts`.
 *
 * The generated hook is called `use<PascalName>Channel` (Vue uses
 * the `use*` prefix for composables) and exposes:
 *
 *   - `state` as a `Ref<ChannelState>`
 *   - `isOpen` as a `ComputedRef<boolean>`
 *   - `send` (only if the channel has client messages)
 *   - `close()` convenience
 *   - typed `onXxx` callback options for every server message
 *
 * If the channel declares a server message named `error`, `onError`
 * is routed to that message (domain wins over lifecycle), matching
 * the vanilla channel-generator's collision resolution.
 */

import type { Channel, SchemaNode } from '@triad/core';
import { TypeEmitter } from '@triad/tanstack-query';

export interface EmittedVueHook {
  path: string;
  contents: string;
  baseName: string;
  hookName: string;
  typeImports: string[];
}

function toPascalCase(name: string): string {
  return name
    .replace(/[_-]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function toKebabCase(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}

function messageToHandlerName(messageType: string): string {
  return `on${toPascalCase(messageType)}`;
}

const TYPE_REF_RE = /\b([A-Z][A-Za-z0-9_]*)\b/g;
const BUILTIN = new Set([
  'Array',
  'Record',
  'Partial',
  'Readonly',
  'ReadonlyArray',
  'Promise',
  'Map',
  'Set',
  'Date',
  'Buffer',
  'Uint8Array',
  'ArrayBuffer',
]);

function collectTypeRefs(type: string, out: Set<string>): void {
  let match: RegExpExecArray | null;
  TYPE_REF_RE.lastIndex = 0;
  while ((match = TYPE_REF_RE.exec(type)) !== null) {
    const ref = match[1]!;
    if (!BUILTIN.has(ref)) out.add(ref);
  }
}

function walkInlineShape(
  emitter: TypeEmitter,
  model:
    | {
        readonly shape?: Record<string, SchemaNode>;
      }
    | undefined,
  typeImports: Set<string>,
): void {
  if (!model || !model.shape) return;
  for (const fieldSchema of Object.values(model.shape)) {
    const typeStr = emitter.emitType(fieldSchema);
    collectTypeRefs(typeStr, typeImports);
  }
}

export function emitChannelVueHook(
  channel: Channel,
  emitter: TypeEmitter,
): EmittedVueHook {
  const baseName = toPascalCase(channel.name);
  const hookName = `use${baseName}Channel`;
  const kebab = toKebabCase(channel.name);
  const typeImports = new Set<string>();

  walkInlineShape(emitter, channel.connection.params, typeImports);
  walkInlineShape(emitter, channel.connection.query, typeImports);
  walkInlineShape(emitter, channel.connection.headers, typeImports);

  interface MsgRef {
    type: string;
    tsType: string;
  }
  const clientMessages: MsgRef[] = [];
  for (const [type, config] of Object.entries(channel.clientMessages)) {
    const tsType = emitter.emitType(config.schema);
    collectTypeRefs(tsType, typeImports);
    clientMessages.push({ type, tsType });
  }
  const serverMessages: MsgRef[] = [];
  for (const [type, config] of Object.entries(channel.serverMessages)) {
    const tsType = emitter.emitType(config.schema);
    collectTypeRefs(tsType, typeImports);
    serverMessages.push({ type, tsType });
  }

  const hasClientMessages = clientMessages.length > 0;
  const hasServerMessages = serverMessages.length > 0;
  const hasErrorMessage = serverMessages.some((m) => m.type === 'error');

  const lines: string[] = [];
  lines.push('// Generated by @triad/channel-client — do not edit.');
  lines.push(
    '// Regenerate with: triad frontend generate --target channel-client-vue',
  );
  lines.push('');
  lines.push(
    "import { watch, type ComputedRef, type Ref } from 'vue';",
  );
  lines.push(
    "import { useTriadChannelLifecycle } from './vue-runtime.js';",
  );
  const factoryImports = [
    `create${baseName}Client`,
    `type ${baseName}Client`,
    `type ${baseName}ClientOptions`,
  ];
  lines.push(
    `import { ${factoryImports.join(', ')} } from './${kebab}.js';`,
  );
  lines.push("import type { ChannelState } from './client.js';");
  if (typeImports.size > 0) {
    const sorted = Array.from(typeImports).sort();
    lines.push(`import type { ${sorted.join(', ')} } from './types.js';`);
  }
  lines.push('');

  if (hasErrorMessage) {
    lines.push('/**');
    lines.push(
      " * This channel declares an `error` server message, so `onError` delivers the channel's `error` server message",
    );
    lines.push(
      ' * (the domain error), not a lifecycle error event. Use the vanilla client directly if you',
    );
    lines.push(' * need to observe socket-level errors.');
    lines.push(' */');
  }
  lines.push(
    `export interface Use${baseName}ChannelOptions extends ${baseName}ClientOptions {`,
  );
  lines.push(
    '  /** When `false`, the hook does not open the channel. Default: `true`. */',
  );
  lines.push('  enabled?: Ref<boolean> | boolean;');
  for (const m of serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push(`  ${handler}?: (payload: ${m.tsType}) => void;`);
  }
  lines.push('}');
  lines.push('');

  lines.push(`export interface Use${baseName}ChannelResult {`);
  lines.push('  /** Reactive channel state. */');
  lines.push('  state: Ref<ChannelState>;');
  lines.push("  /** Computed flag equivalent to `state.value === 'open'`. */");
  lines.push('  isOpen: ComputedRef<boolean>;');
  if (hasClientMessages) {
    lines.push('  /** Typed outbound message surface. */');
    lines.push(`  send: ${baseName}Client['send'];`);
  }
  lines.push(
    '  /** Close the channel. Called automatically on component unmount. */',
  );
  lines.push('  close: () => Promise<void>;');
  lines.push('}');
  lines.push('');

  lines.push(
    `export function ${hookName}(options: Use${baseName}ChannelOptions): Use${baseName}ChannelResult {`,
  );
  const destructured = ['enabled'];
  for (const m of serverMessages) {
    destructured.push(messageToHandlerName(m.type));
  }
  destructured.push('...clientOptions');
  lines.push(`  const { ${destructured.join(', ')} } = options;`);
  lines.push('');
  lines.push('  const { client, state, isOpen } = useTriadChannelLifecycle(');
  lines.push(`    () => create${baseName}Client(clientOptions),`);
  lines.push('    { enabled },');
  lines.push('  );');
  lines.push('');

  if (hasClientMessages) {
    lines.push(`  const send: ${baseName}Client['send'] = new Proxy(`);
    lines.push(`    {} as ${baseName}Client['send'],`);
    lines.push('    {');
    lines.push('      get(_target, prop): unknown {');
    lines.push('        return (payload: unknown): void => {');
    lines.push('          const current = client.value;');
    lines.push('          if (current === null) {');
    lines.push(
      "            throw new Error('Cannot send on a disabled or closed channel.');",
    );
    lines.push('          }');
    lines.push(
      '          (current.send as unknown as Record<string, (p: unknown) => void>)[prop as string]!(payload);',
    );
    lines.push('        };');
    lines.push('      },');
    lines.push('    },');
    lines.push('  );');
    lines.push('');
  }

  // Attach/detach message listeners. Vue's `watch(client, ...)` runs
  // whenever the client ref changes (setup/teardown edges); the
  // cleanup function it passes releases the previous subscription.
  for (const m of serverMessages) {
    const handler = messageToHandlerName(m.type);
    lines.push('  watch(');
    lines.push('    client,');
    lines.push('    (current, _prev, onCleanup): void => {');
    lines.push(`      if (current === null || !${handler}) return;`);
    lines.push(`      const unsubscribe = current.on('${m.type}', ${handler});`);
    lines.push('      onCleanup(() => unsubscribe());');
    lines.push('    },');
    lines.push('    { immediate: true },');
    lines.push('  );');
    lines.push('');
  }

  lines.push('  return {');
  lines.push('    state,');
  lines.push('    isOpen,');
  if (hasClientMessages) {
    lines.push('    send,');
  }
  lines.push('    close: async (): Promise<void> => {');
  lines.push('      const current = client.value;');
  lines.push('      if (current !== null) await current.close();');
  lines.push('    },');
  lines.push('  };');
  lines.push('}');
  lines.push('');

  void hasServerMessages;

  return {
    path: `${kebab}-vue.ts`,
    contents: lines.join('\n'),
    baseName,
    hookName,
    typeImports: Array.from(typeImports),
  };
}
